<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Enda Flynn">
<meta name="dcterms.date" content="2024-07-29">

<title>MLR - Weight Loss Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="mlr_weight_loss_files/libs/clipboard/clipboard.min.js"></script>
<script src="mlr_weight_loss_files/libs/quarto-html/quarto.js"></script>
<script src="mlr_weight_loss_files/libs/quarto-html/popper.min.js"></script>
<script src="mlr_weight_loss_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="mlr_weight_loss_files/libs/quarto-html/anchor.min.js"></script>
<link href="mlr_weight_loss_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="mlr_weight_loss_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="mlr_weight_loss_files/libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="mlr_weight_loss_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="mlr_weight_loss_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="mlr_weight_loss_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="mlr_weight_loss_files/libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">

<script src="mlr_weight_loss_files/libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<link href="mlr_weight_loss_files/libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="mlr_weight_loss_files/libs/datatables-binding-0.22/datatables.js"></script>
<script src="mlr_weight_loss_files/libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="mlr_weight_loss_files/libs/dt-core-1.11.3/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="mlr_weight_loss_files/libs/dt-core-1.11.3/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="mlr_weight_loss_files/libs/dt-core-1.11.3/js/jquery.dataTables.min.js"></script>
<link href="mlr_weight_loss_files/libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet">
<script src="mlr_weight_loss_files/libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#multiple-regression-model" id="toc-multiple-regression-model" class="nav-link" data-scroll-target="#multiple-regression-model">Multiple Regression Model</a>
  <ul class="collapse">
  <li><a href="#model-specification" id="toc-model-specification" class="nav-link" data-scroll-target="#model-specification">Model Specification</a></li>
  <li><a href="#interpret-the-estimates-of-the-parameters" id="toc-interpret-the-estimates-of-the-parameters" class="nav-link" data-scroll-target="#interpret-the-estimates-of-the-parameters">Interpret the Estimates of the Parameters</a></li>
  <li><a href="#which-values-of-the-categorical-predictor-variables-will-lead-to-the-largest-reduction-in-weight" id="toc-which-values-of-the-categorical-predictor-variables-will-lead-to-the-largest-reduction-in-weight" class="nav-link" data-scroll-target="#which-values-of-the-categorical-predictor-variables-will-lead-to-the-largest-reduction-in-weight">Which values of the categorical predictor variables will lead to the largest reduction in weight?</a></li>
  <li><a href="#the-effect-and-significance-of-the-categorical-variable-routine-in-our-model." id="toc-the-effect-and-significance-of-the-categorical-variable-routine-in-our-model." class="nav-link" data-scroll-target="#the-effect-and-significance-of-the-categorical-variable-routine-in-our-model.">The effect and significance of the categorical variable <strong>routine</strong> in our model.</a></li>
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing">Hypothesis Testing</a>
  <ul class="collapse">
  <li><a href="#interpreting-the-f-statistic" id="toc-interpreting-the-f-statistic" class="nav-link" data-scroll-target="#interpreting-the-f-statistic">Interpreting the F-statistic</a></li>
  <li><a href="#testing-the-hypothesis-h_0-beta_1-beta_2-0" id="toc-testing-the-hypothesis-h_0-beta_1-beta_2-0" class="nav-link" data-scroll-target="#testing-the-hypothesis-h_0-beta_1-beta_2-0">Testing the hypothesis <span class="math inline">\(H_0: \beta_1 = \beta_2 = 0\)</span></a></li>
  </ul></li>
  <li><a href="#interpreting-the-adjusted-r-squared-value" id="toc-interpreting-the-adjusted-r-squared-value" class="nav-link" data-scroll-target="#interpreting-the-adjusted-r-squared-value">Interpreting the Adjusted R-squared Value</a></li>
  <li><a href="#predicting-weight-loss" id="toc-predicting-weight-loss" class="nav-link" data-scroll-target="#predicting-weight-loss">Predicting Weight Loss</a>
  <ul class="collapse">
  <li><a href="#prediction-interval-for-predicted-weight-loss" id="toc-prediction-interval-for-predicted-weight-loss" class="nav-link" data-scroll-target="#prediction-interval-for-predicted-weight-loss">95% Prediction Interval for Predicted Weight Loss</a></li>
  </ul></li>
  <li><a href="#interaction-effects" id="toc-interaction-effects" class="nav-link" data-scroll-target="#interaction-effects">Interaction Effects</a>
  <ul class="collapse">
  <li><a href="#modelling-the-interaction" id="toc-modelling-the-interaction" class="nav-link" data-scroll-target="#modelling-the-interaction">Modelling the Interaction</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#diagnostic-tests-on-the-regression-model" id="toc-diagnostic-tests-on-the-regression-model" class="nav-link" data-scroll-target="#diagnostic-tests-on-the-regression-model">Diagnostic tests on the regression model</a>
  <ul class="collapse">
  <li><a href="#linearity-assumption" id="toc-linearity-assumption" class="nav-link" data-scroll-target="#linearity-assumption">Linearity Assumption</a>
  <ul class="collapse">
  <li><a href="#scatterplots" id="toc-scatterplots" class="nav-link" data-scroll-target="#scatterplots">Scatterplots</a></li>
  <li><a href="#added-variable-plots" id="toc-added-variable-plots" class="nav-link" data-scroll-target="#added-variable-plots">Added Variable Plots</a></li>
  </ul></li>
  <li><a href="#added-variable-plots-in-detail" id="toc-added-variable-plots-in-detail" class="nav-link" data-scroll-target="#added-variable-plots-in-detail">Added Variable Plots in Detail</a>
  <ul class="collapse">
  <li><a href="#interpretations-for-all-predictor-variables-in-the-model" id="toc-interpretations-for-all-predictor-variables-in-the-model" class="nav-link" data-scroll-target="#interpretations-for-all-predictor-variables-in-the-model">Interpretations for all predictor variables in the model</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#anova" id="toc-anova" class="nav-link" data-scroll-target="#anova">ANOVA</a>
  <ul class="collapse">
  <li><a href="#anova-type-i" id="toc-anova-type-i" class="nav-link" data-scroll-target="#anova-type-i">ANOVA Type I</a></li>
  <li><a href="#anova-type-ii" id="toc-anova-type-ii" class="nav-link" data-scroll-target="#anova-type-ii">ANOVA Type II</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">MLR - Weight Loss Data</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Enda Flynn </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 29, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><em>Note that you can collapse the code using the button on the top right to focus on the analysis.</em></p>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>This analysis will focus on applying multiple linear regression to the weight loss data set.</p>
<p>In this analysis, we will cover:</p>
<ul>
<li>Fitting a multiple linear regression model to the data</li>
<li>Interpreting the estimates for the continuous and categorical predictors in the model</li>
<li>Model diagnostics with scatterplots and added variable plots</li>
<li>Type 1 and Type 2 ANOVA tests</li>
</ul>
</section>
<section id="multiple-regression-model" class="level1">
<h1>Multiple Regression Model</h1>
<section id="model-specification" class="level2">
<h2 class="anchored" data-anchor-id="model-specification">Model Specification</h2>
<p>We begin by loading the necessary libraries and the data set - we can explore this interactively in the table below to get a sense of the</p>
<div class="cell">

</div>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"data/weight_loss.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">datatable</span>(df, <span class="at">options =</span> <span class="fu">list</span>(<span class="at">pageLength =</span> <span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">

<div id="htmlwidget-f09716097fdddea908d7" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-f09716097fdddea908d7">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88","89","90","91","92","93","94","95","96","97","98","99","100","101","102","103","104","105","106","107","108","109","110","111","112","113","114","115","116","117","118","119","120","121","122","123","124","125","126","127","128","129","130","131","132","133","134","135","136","137","138","139","140","141","142","143","144","145","146","147","148","149","150","151","152","153","154","155","156","157","158","159","160","161","162","163","164","165","166","167","168","169","170","171","172","173","174","175","176","177","178","179","180","181","182","183","184","185","186","187","188","189","190","191","192","193","194","195","196","197","198","199","200","201","202","203","204","205","206","207","208","209","210","211","212","213","214","215","216","217","218","219","220","221","222","223","224","225","226","227","228","229","230","231","232","233","234","235","236","237","238","239","240","241","242","243","244","245","246","247","248","249","250","251","252","253","254","255","256","257","258","259","260","261","262","263","264","265","266","267","268","269","270","271","272","273","274","275","276","277","278","279","280","281","282","283","284","285","286","287","288","289","290","291","292","293","294","295","296","297","298","299","300","301","302","303","304","305","306","307","308","309","310","311","312","313","314","315","316","317","318","319","320","321","322","323","324","325","326","327","328","329","330","331","332","333","334","335","336","337","338","339","340","341","342","343","344","345","346","347","348","349","350","351","352","353","354","355","356","357","358","359","360","361","362","363","364","365","366","367","368","369","370","371","372","373","374","375","376","377","378","379","380","381","382","383","384","385","386","387","388","389","390","391","392","393","394","395","396","397","398","399","400","401","402","403","404","405","406","407","408","409","410","411","412","413","414","415","416","417","418","419","420","421","422","423","424","425","426","427","428","429","430","431","432","433","434","435","436","437","438","439","440","441","442","443","444","445","446","447","448","449","450","451","452","453","454","455","456","457","458","459","460","461","462","463","464","465","466","467","468","469","470","471","472","473","474","475","476","477","478","479","480","481","482","483","484","485","486","487","488","489","490","491","492","493","494","495","496","497","498","499","500","501","502","503","504","505","506","507","508","509","510","511","512","513","514","515","516","517","518","519","520","521","522","523","524","525","526","527","528","529","530","531","532","533","534","535","536","537","538","539","540","541","542","543","544","545","546","547","548","549","550","551","552","553","554","555","556","557","558","559","560","561","562","563","564","565","566","567","568","569","570","571","572","573","574","575","576","577","578","579","580","581","582","583","584","585","586","587","588","589","590","591","592","593","594","595","596","597","598","599","600"],[35.78457503,26.16519901,29.55366447,-6.223291449,17.16419563,11.36594786,50.21628985,9.961046838,19.08853873,-0.058835726,10.1864161,-2.254144514,-0.717068014,-0.371782083,-4.504618583,-6.239632655,20.80939197,36.68035466,1.619956977,34.77525404,3.035435425,8.620310105,39.14494345,-8.192091699000001,-1.936153269,29.12292079,35.84628859,22.6435271,0.467520436,14.24258864,7.964996042,-7.049739918,-2.999005451,36.6118442,7.704889295,5.158278347,16.02469603,24.32610565,20.6910045,23.33835954,3.268562088,0.792060299,30.64547137,8.481442864,-10.07638194,25.56539208,30.00851699,27.29555458,-6.681346661,20.82058334,37.47627851,16.79937208,4.224647918,15.6408396,43.22065704,31.43912914,14.21799116,-1.300106891,-2.442135951,43.57867093,22.94252157,-2.105109405,23.2754496,-5.700818223,-1.012727271,18.13423786,-7.194164799,11.62768274,-7.477804737,-6.068613682,-9.950435521999999,30.49746374,27.51187325,15.60524203,-4.837634001,20.79209444,-2.528890292,1.222189202,5.068046623,-4.881504692,11.67515143,6.31555152,-3.761451385,12.61147525,23.28355127,-1.386409156,7.764951976,-1.716197726,3.78082671,25.27845544,31.57136705,27.63675581,-2.836819394,14.99795422,1.842724946,34.76041975,-9.511893061,34.71352102,15.77436777,-3.466760375,-2.537579641,-7.517040424,27.33961867,-10.82715198,42.90003153,17.83907926,19.74727553,-7.958889202,-10.04734016,31.02447209,18.21847509,-10.20484178,1.876790997,-1.626913099,11.01937509,0.129009103,-1.027258735,-8.156792636,4.569408107,5.177439695,35.12073768,-2.492719305,0.192628323,12.26136116,-1.246788854,-2.19670526,21.92186203,22.40266404,-7.458791074,-3.74332552,-0.906307575,35.78260471,20.00499461,-9.345355874999999,23.26829519,-5.907087679,-0.746444962,-13.13797745,15.5684311,-5.666496566,-0.951814966,-6.945145033,-0.730972165,2.392752731,-10.52058235,-9.65615998,35.39438433,44.82609305,7.918722829,11.8782301,2.692732381,15.52679561,10.96223704,11.94964001,18.96260536,7.289008633,-2.36344045,29.60208322,20.28009693,18.6180622,15.59220953,-1.60125286,0.339197565,-8.89390476,-3.340374261,3.910847304,44.35966969,-7.840372001,50.20277462,24.45204551,-5.419889222,-1.461044038,22.26190127,19.25182693,14.44806105,35.69708322,26.32729535,15.79836076,-9.250049217999999,21.54374981,-5.075015368,36.69029958,5.99772217,15.7945578,34.02687139,15.70531937,-0.172356265,5.028615981,-2.920444589,-3.591117595,27.50592848,-7.986700847,-9.438920396,-0.97108884,-9.365391239999999,-8.326285906000001,-1.597577769,-2.845429883,-6.541708695,14.9522118,7.326626955,-7.379213193,-8.321042133000001,23.48211003,27.56836562,35.69404088,-2.251965781,15.71459124,4.273839565,-6.851943024,-3.090760525,1.311990577,-1.890469051,-9.307244170000001,28.47026479,-9.732437147000001,15.98512072,-9.488060742,-7.823982786,-0.803155733,-3.406134184,-6.42200138,-7.276312767,33.89378124,-7.976544959,17.97193542,-6.580212456,30.25723683,-8.814620506000001,-7.991696346,-0.50028508,13.67138281,-7.719199357,-1.389572851,41.08519228,34.32243459,31.66324526,13.72855508,5.331616798,37.12969191,7.57126979,34.60024817,27.41584981,-6.685690064,-0.909746717,-5.624189224,5.131908375,10.44765222,-13.50038508,-0.691277458,-13.37007001,-8.093298430000001,11.05737087,4.210993574,25.38745459,22.36233727,-4.10602848,17.52441234,-5.121288776,17.71343241,14.87570237,17.67765216,-7.910385432,4.924681128,48.9834673,5.341769172,-2.779765229,-12.52011221,38.89903609,19.78508366,7.848263756,10.04821927,8.70997747,-9.315924147,4.913901004,28.96284443,27.56027169,13.22021777,14.87561623,33.48331377,0.588966095,8.385867792999999,-0.775082846,-5.984424564,27.74957805,15.44003102,19.87449036,-6.553905529,-5.573334519,7.004230157,24.92584579,31.68013916,-0.480100715,2.901078304,5.121604098,0.324854124,18.41236543,26.96965479,42.0529412,-11.06019306,23.13444284,6.505865472,-2.948409308,0.492137842,20.05642597,-1.352902944,-6.354554676,1.326611674,18.52140651,25.79421597,-5.699962691,-8.509472129000001,-6.334067586,-1.699508247,1.75032988,-2.165881295,-8.981669953999999,25.60492106,-1.817629888,-4.238788772,-0.6788903509999999,19.07106893,36.16556269,37.22547433,-4.124550776,10.6590941,7.953929392,21.91954862,2.154387979,2.626247544,2.482240575,14.66675168,24.1238264,0.541262817,8.382513517,27.60935272,0.89343488,5.635589191,3.244533042,-9.720744735,12.60598158,9.77091525,-0.109905246,21.23901832,-4.040597677,15.49346497,18.00451462,0.997138173,10.5263018,31.90455755,23.15509779,-5.715562046,0.806542062,4.657062695,5.054321226,16.35911375,2.5160831,0.058067871,-5.673433154,-6.294695106,38.39194393,4.715287834,-5.121669535,-0.310234691,-1.385646123,19.90712252,4.265271938,17.80410435,18.19866129,12.42335576,14.17856631,29.2035969,-6.093350717,-2.348057412,-0.82461873,2.933700023,-0.36038718,12.33513618,11.32236764,35.12439628,-9.649648150000001,18.35811478,3.908003888,-6.938595931,1.455699895,15.84447684,2.437959436,26.97861841,-5.238561486,5.602395154,5.77876483,16.73770261,5.736233121,14.17379765,41.14938387,3.583152031,-4.68569449,-4.473627524,3.181888442,-4.377123097,10.07128506,11.32965765,28.88026152,15.28219404,34.70042157,13.00967528,21.67458248,-4.938184375,2.128255816,12.53730936,11.453814,19.08060871,17.68641374,3.309688383,3.342454461,11.38529149,1.142504042,20.70888687,11.20632988,19.06512394,3.350044477,8.694731043000001,23.45931025,8.774950882000001,-0.255612702,-6.442069486,-5.676177296,8.697034788,-7.008538336,-1.529615358,13.48562696,1.666442026,0.9308357350000001,-1.401660698,38.41105663,15.91945363,19.69473057,11.43404611,29.17036382,31.4187261,12.14168351,16.67833765,10.23557674,-4.645074293,8.307973105,14.51559546,10.04111782,14.79979909,13.15320116,5.328760564,-3.455820342,-1.839466779,21.17070981,18.02226347,5.879858991,-1.037460765,-1.29589832,13.4723914,34.67400743,13.28283615,13.30411104,-9.096559349,10.97832564,19.71117922,6.485834934,-9.125625506,29.58596994,7.448606388,29.44659903,2.342692639,-5.230564853,14.39829835,-4.932004495,12.16574219,13.28714885,-9.814887321,11.97272982,-0.516719007,19.77726866,38.66590492,30.13954607,16.36109531,-5.670458103,20.04647904,1.633664394,16.99576672,2.172546542,-13.21819316,15.81145021,-9.813676167000001,35.08693434,-8.666867972,45.93037141,7.170091896,-5.477191707,-5.186867731,7.305182996,1.39712755,35.98798987,17.07517148,-4.046370598,30.27662028,-8.775116484,39.57021226,-0.108963695,-9.641093572999999,37.39421211,6.569895608,40.20039784,18.42574661,-2.68405281,25.47968135,19.42000193,23.38302643,-1.207556718,30.71243502,-0.722880267,18.59235488,11.98087867,-7.065053688,18.34637681,-3.69574164,0.64142394,11.21288973,-2.794565191,16.8399122,-4.197730154,27.6027708,17.32589992,9.943101505,8.292644749999999,27.7718869,27.30329439,30.03082682,13.97257238,11.93027462,13.41703999,22.5708634,-0.217715881,-7.981870261,11.78908038,23.30085409,13.76516067,-9.583974414,2.931162894,18.0908656,40.95153889,13.3028305,31.0558431,0.876391319,0.001279143,-2.556869108,-1.184700004,13.52134668,-6.377654524,35.48160024,17.66896959,-2.167520261,2.66071274,1.678461433,-4.034349656,-1.935769058,-7.654033775,10.13891289,28.5995445,12.23964809,-3.412543222,9.472298049999999,16.75191688,22.91107209,-7.771700587,-5.087228721,12.18365929,11.50818258,33.53030236,7.559304217,8.594281029999999,6.600820391,6.761342126,54.15045951,-4.624109237,5.92889061,29.99856864,21.70197378,22.42597715,-2.670946752,39.92294152,2.130261816,-7.628575558,-3.407904679,-6.190263385,35.99983718,3.971017692,12.29824101,33.34206812,16.66086992,-6.963694613,-0.631100743,-1.398119446,11.7246702],[2.531527926,2.061786025,2.114789836,1.804308169,1.414858429,1.834287042,2.876910983,2.691039384,1.992727062,1.716943247,2.389360188,2.604619458,2.226287728,2.36711576,2.783031993,2.282757215,1.341594147,2.176959601,1.947049123,2.167177707,1.31238866,1.604954472,2.138779117,3.196274307,1.284130043,1.940796788,2.081584311,1.86971757,1.849433818,1.889827666,2.308163021,1.661891241,1.8023201,2.197148788,1.767425767,1.493375919,1.594147113,2.18240802,2.499087932,1.560945536,2.298609142,1.784127695,2.509975392,1.269769325,3.094100263,2.291886082,3.063947721,2.794003646,2.361482496,1.820589432,2.217347396,1.309415562,1.974831741,1.784753448,2.556693816,2.194668316,1.9889973,0.896931353,2.4739901,2.503847613,1.680497355,2.078306927,2.836301053,1.703450747,2.432544683,1.986257889,2.088690791,2.053212484,1.502064487,1.677151147,2.030226678,2.281359872,1.721852372,2.538934023,1.500328865,1.955140946,1.502512286,1.456378669,1.856932002,1.785803226,1.73719553,1.336735664,1.670534493,1.598363272,1.307603108,1.639186079,2.173681627,1.396249774,1.685848808,2.212687039,1.990206501,2.032332699,3.527963728,1.140314608,1.811812389,2.085153014,2.639485964,1.309536886,2.749366682,2.026160725,1.817270386,2.367523263,1.915304989,2.65733078,2.107128144,2.091647444,2.362116791,1.891746258,2.481272794,2.497556766,2.337162349,1.95700929,1.936338421,1.510283551,1.236609379,1.746601085,1.03944932,2.083556968,1.568050277,2.10742639,1.563534953,1.626664709,1.956391034,1.823261571,1.117538241,1.952946276,3.08876034,2.507860811,1.874887076,1.652388998,2.348580487,1.539290494,2.02187091,2.341334178,1.659796519,2.368127517,1.813176895,1.13567452,2.032899031,2.078485976,0.926837909,2.978440711,1.962117806,1.554349932,2.4809654,2.094811715,1.988079013,2.070897712,1.744685408,1.511545452,2.445261377,2.556611438,1.734408076,1.000784944,2.420892728,2.120418115,1.955969872,2.459005008,2.041124505,2.242624413,2.354275492,1.985213881,1.909882559,1.972551737,1.678557747,1.614455145,2.591660935,1.7849241,1.88931581,1.834708847,2.492061651,0.590529041,1.144735418,1.657993903,2.269551093,3.038235473,1.568967118,2.498399122,1.621747105,2.354044088,1.282200094,2.400119105,1.907683682,2.840855889,1.868967575,2.486482198,1.724371638,2.170512167,2.393799083,2.229776748,1.838634638,2.201028581,1.617011197,2.28847509,2.101664332,2.416849021,1.76516397,1.336293868,2.398447921,1.493437209,2.127043509,2.248475253,2.191040962,1.046925265,2.036461517,2.607528719,1.883230718,1.457733776,1.1184937,2.420950707,2.257886934,1.8106943,1.47229584,2.245473753,1.68764378,2.217633088,2.195378232,2.469575303,2.35309688,1.557110735,1.654657658,1.53717737,2.68491296,1.344405846,1.241355703,2.811353378,2.59698369,1.673999234,3.186396509,2.78186449,1.653684858,1.358517108,2.450468279,1.276135991,2.283249331,1.871858106,2.007659584,0.649647227,2.181436893,3.115876709,1.881600897,2.042050099,1.330098314,3.273179704,2.115096663,1.938958545,1.605326946,2.601102489,2.413041153,2.118086199,2.841171277,2.173335686,2.279594458,2.198402564,2.044154949,2.394756335,2.180020382,2.160932977,2.482672127,1.379335674,1.467503672,1.817667377,1.916195354,2.157454429,2.500447873,1.198850966,1.443948023,3.177911813,2.365800447,1.780035735,1.977653407,2.558896756,1.556859932,2.861772689,1.571172554,2.334119157,1.854208469,2.379161051,1.936462544,1.76646481,2.079213409,1.534771789,1.446103067,1.841891974,1.310060584,0.987037958,2.301792324,1.91780522,1.327328872,1.697761253,2.422519245,1.811440227,1.434908794,1.793691182,2.217564644,1.278743745,1.922653607,2.192430051,2.558688863,1.114307965,2.292181,1.48123187,1.918691579,2.338049673,3.206742519,1.980110862,2.513327676,1.362825296,1.810092133,2.012166906,2.029083372,2.33351186,2.386256555,1.400021322,1.950479828,1.379310421,2.552315059,2.24059797,1.266677421,2.695610784,2.585333295,2.128824874,2.365756212,1.617238089,1.672399596,3.008793819,2.36937552,2.229815056,1.681851911,1.809473313,1.919233305,2.671987239,0.922618745,1.569652318,1.863657214,2.096233194,2.751950456,2.226117028,1.757641564,1.761989554,1.529283229,1.315054629,1.599533757,1.894243809,1.292630055,1.957242781,1.414927837,2.778892931,1.263867819,2.280710737,1.698828958,2.991679567,1.770592573,2.218057886,2.625107888,2.040241268,1.581508651,1.755787517,2.109731074,1.491875549,2.513379875,2.2089628,1.858161091,2.487408746,1.556959025,1.302580802,2.451113085,2.015928988,1.942664005,2.356751243,2.866532748,2.078051797,1.50450702,2.684325703,1.771326736,1.644862795,2.283878839,1.244143557,2.394859708,2.0233771,2.795217785,2.150921195,2.069263702,2.78516343,1.357774607,1.766257821,2.241957736,2.054469916,2.052051609,1.927567626,1.992681061,2.746028843,2.466410124,1.275615952,2.622807584,1.464838998,1.682702489,2.41067642,1.970742386,1.585122236,2.708712968,0.887997584,1.778971683,1.357664322,1.678705343,1.86565959,2.338392784,2.592059074,2.01007338,2.370960937,2.584304019,1.390029064,0.743567735,2.552154451,1.160197925,1.540869088,1.919179649,2.290251207,1.047257528,2.042378182,2.353564917,2.217030678,2.835298346,1.523482744,1.34198052,2.097209035,1.180744597,1.591763435,2.001866034,1.146826837,2.100871236,1.901250443,1.994466389,1.983931487,2.566908974,1.949650679,2.367161891,2.509460586,2.03703556,2.211334662,2.94277753,2.088084089,1.691441867,3.05318975,2.099675607,2.631421062,2.393726377,2.225257342,2.196270043,1.523157248,2.115194612,1.916530944,1.767524465,1.836703542,1.609936322,2.232247165,1.516275534,2.096936619,2.627456344,2.41101828,2.45893644,1.75335714,2.039479289,2.614809245,2.069974971,2.622450745,1.342230003,2.238887607,1.442526434,2.148499625,1.687870351,2.39351732,1.399631898,1.791984309,2.428878799,2.751063267,1.953491937,1.827602919,2.068969717,2.141997882,2.635346719,1.885167516,2.68004924,2.015003759,1.766976923,2.128768127,1.708885006,2.116325164,3.227836588,1.450901427,2.238611409,2.36275363,2.13156217,1.43485331,0.668341632,1.565308299,2.721077229,2.156243732,2.660179526,2.108369825,1.223838621,1.883926832,2.316557792,1.911170034,1.69617632,1.900590261,2.128397391,2.273168243,2.474727584,1.630171676,1.757690627,2.13428723,2.623871724,2.266467562,1.64449102,2.554038731,2.70159358,1.3326207,2.244969442,2.319627237,1.190844402,1.717420419,1.846662096,2.49305416,2.389998481,1.924600943,1.577579856,1.922411705,2.526068921,1.517399257,1.979328574,1.545225838,2.877839343,1.377906104,2.373511503,1.503160705,2.332479029,2.628351282,2.000053995,2.178331253,1.918619028,1.847636947,1.977410817,2.125429694,0.864675741,2.194921374,2.044920841,2.12456531,1.744949828,1.800114298,2.394883432,1.488264507,1.702563201,1.504226841,2.092936405,1.797834106,2.366035633,1.748953703,1.534196235,1.632590359,1.760331502,1.410553944,1.930707408,1.162022664,1.180935009,2.648500054,1.519792901,1.432426557,1.837277411,1.747350709,2.16046839,2.031416162,2.004228765,1.480263886,1.48519906,2.309262784,1.399858084,1.363075456,2.29968755,2.546024432,1.334598347,1.372820754,1.864663226,1.976761944,1.621447774,2.297189873,2.130919067,1.904569774,2.588904668,2.166252514,1.039580789,2.233682402,1.840893735,2.324240204,2.683453176,1.540172946,1.887181303,1.529990611,2.602159423,1.949107964],[28.81869069,27.39480918,29.93530287,35.85175623,28.68674517,31.30938152,42.24629155,28.48640167,29.43055814,26.71493372,26.72401476,28.10625713,34.86822787,28.19652322,31.41398766,26.78112107,25.94535631,29.52562456,27.85054324,34.47848136,29.01781554,25.11583713,37.7849071,25.50540982,18.76290489,29.92033983,37.17971758,25.15082311,29.62932874,24.72711748,24.28701424,32.39611532,26.08717835,31.22832817,24.83447466,33.56646327,28.08084536,28.97862574,34.39723084,35.29382204,31.34896198,31.90897425,32.95585014,30.07202991,23.71824026,26.26725957,26.28897017,30.2126321,26.82530463,28.27278121,36.72480691,37.94804383,37.92187803,26.08708643,35.96156978,30.95580429,24.97051687,29.54852441,29.08540966,35.86348894,32.5283664,26.08781165,41.91518301,32.4013914,22.55666096,27.94240201,26.48597443,33.26178493,17.7440607,25.41179942,24.1569485,25.93881554,31.4812329,34.01433625,22.28541002,37.27440926,38.09892865,17.51012882,27.64677892,30.8639717,18.53790261,28.39070841,28.2933344,16.63726674,35.30143554,24.13370875,32.91435978,29.13072226,34.02522757,24.42246076,32.82480617,28.11690001,30.59482925,32.73352964,25.87173844,36.58816938,32.26129356,34.38663066,20.10621149,23.11749319,35.53602107,37.14500528,29.97039453,28.40521409,37.23258128,23.5935043,36.31657283,23.54267968,32.0137049,31.33714817,27.6859638,33.91885009,26.70302051,32.95040819,33.7114454,35.17494979,30.75052849,22.48743896,36.63718303,27.12199798,41.76586007,35.0454218,19.7921834,40.44694102,29.86124436,36.00666593,22.94163151,21.48337317,31.64544191,24.34279387,25.7384717,30.44944734,23.21355936,30.00901636,37.18331551,35.31361538,28.24339936,27.62332516,32.75854843,23.33056108,31.03594914,30.29884146,25.63746373,27.6127789,27.10190278,36.94775799,32.45922602,41.64810172,33.65265155,34.39730005,37.02448576,34.74464748,29.30078439,29.50746406,42.50158879,31.00376916,20.33880644,34.67442562,30.52757463,27.68813956,32.40808178,26.59437736,30.43334116,30.43082266,23.35265096,27.89900404,34.95991477,25.14869211,38.6385605,24.85388909,29.39806408,31.73791661,29.75178188,34.04354337,41.01456569,33.92383127,25.26471525,32.63693126,27.43458176,27.08206297,35.01888746,34.87442473,27.68683796,31.86554769,32.40447331,21.41099036,28.49321136,19.15406788,40.40285613,28.36922307,30.08515339,26.29817605,23.35459641,26.08732995,33.97354272,33.82102087,18.60373341,24.31203864,29.52059087,29.22192775,33.41549719,21.58943259,27.16482167,24.83995448,29.75966085,32.82779453,23.18954879,37.15931799,26.75165466,37.89977599,23.09235603,29.61140997,17.57202299,22.61122643,27.24492081,26.01851404,20.88501128,35.64671022,31.06734722,27.32527138,36.30789517,39.7881829,29.62526399,35.92233748,23.23980678,28.92750356,32.21795724,31.41182307,23.28740478,33.97203488,30.05279787,29.91107956,34.31758554,20.4082527,39.26553397,33.15664498,32.34578647,32.91468498,23.39117802,30.45158293,42.03012144,30.89672114,30.03280315,35.52727729,33.49094652,30.23855007,20.07828236,26.35253769,27.64919421,24.91890449,27.91081523,25.11073533,33.96202872,24.53648907,29.33328742,25.27893758,15.99855205,25.79619315,28.78894038,32.23818012,26.20171602,30.54148265,26.1697303,33.14165941,37.65540691,33.43691033,29.7536976,31.33497705,36.61303556,23.43206478,36.75557452,29.11949614,21.25832955,25.84665911,37.50555966,29.7406503,28.11873884,32.74524887,29.83005974,32.71353471,19.69528843,28.61803768,18.74474407,27.23592145,30.12553909,26.65733304,27.49243336,30.81528118,28.44524177,24.86326792,25.29827956,36.99534303,32.56142868,27.78269751,32.32343955,31.29398323,35.48685976,32.5405084,39.8282915,27.36217,27.94312294,27.35514886,40.20751169,29.09232811,34.81758382,26.90082709,23.89204269,31.78132911,30.23229859,30.51898138,26.93366334,27.81651196,32.29514479,29.78800362,37.87520118,32.83944262,27.13777389,33.78926551,36.7838834,28.30257396,13.63296265,30.42368676,32.90658877,38.79313859,35.56167293,31.15620201,33.7450652,35.13001449,19.22168856,35.11126239,29.15412247,21.31555623,44.07604078,21.87930415,25.3877601,30.51279172,19.40414301,27.70262134,26.13178018,23.64497792,28.68895002,24.05022729,25.43848597,27.52015902,30.6097225,28.46855664,30.06796207,20.16726293,24.85934733,33.47360468,25.45634844,24.48015059,30.0315938,25.06562402,22.99087782,21.49223952,21.73703532,24.95897687,33.26926303,29.98419189,39.28197883,22.84700237,29.41144802,36.0558183,39.90873221,29.72854204,27.09918704,38.37072433,27.63741337,26.53413459,34.76155893,30.52309119,24.93111607,28.88008148,23.95377739,31.59783807,25.09288402,28.77686179,32.07875784,28.66521541,29.45165337,22.57524143,36.78477571,27.59517263,29.67847458,26.40925774,24.16337824,29.80852549,29.01907415,33.67543063,28.16688013,32.88359418,26.22947511,26.82292089,34.51582399,40.40453852,17.30372199,25.69707946,22.77681941,24.81871545,32.12480037,33.09239775,34.50454655,27.70518002,41.88456184,24.76497026,24.62098554,33.69954858,28.29475384,33.88961015,27.47183801,21.02335497,33.74980498,25.85781631,29.30139136,26.82340361,27.72969121,25.51790303,28.51769572,29.07725135,15.1637539,28.06947272,33.05021749,26.57235809,20.21866051,31.09927973,33.78387814,35.60424126,30.00423609,19.02757777,36.3883663,26.44594811,32.15701512,41.07028654,33.1334571,24.92224591,33.66948321,34.57374678,31.93892424,33.68208452,31.48438723,27.72583714,37.1375777,23.42555323,28.5290929,32.52992818,33.36035291,31.98490502,32.02755668,22.87466175,38.82301588,34.6293156,32.57466289,37.71218433,34.84933716,32.18774107,29.54723001,24.30144647,30.79947193,36.66416353,25.12406555,21.97016419,27.01187716,23.89584931,38.05512148,24.19118269,30.61849712,29.95571335,26.8868424,29.31438698,34.1500884,30.1677127,23.29443144,26.81188231,34.61634082,24.06815715,32.36428122,31.87705816,33.26623603,38.81696692,26.08556817,32.36458954,36.4824262,31.10668729,28.38241978,31.98136225,28.63518486,28.33010447,32.21228643,22.85223392,34.53344772,24.48708029,42.22196354,30.23579748,25.68453254,28.62907392,29.92465021,20.41391035,32.65133648,34.1911079,32.71210202,28.70877248,34.26185073,35.75943291,16.78225048,22.20606549,40.40144085,31.08278017,33.19533322,23.85364585,32.72507461,33.63715919,32.46406812,29.01129138,22.98516424,32.36887547,29.50336133,36.03775904,30.46196585,24.03559871,22.34493518,27.74834598,26.52968382,34.39176553,32.18109184,23.62913269,30.98634776,37.80489728,33.12142422,28.18477543,34.54712411,30.62314826,26.64978799,41.14675117,31.17600742,31.43899823,30.85967885,40.84311094,30.10857933,26.65563392,32.68346727,33.73737728,23.48834091,29.6614032,29.88351049,32.06365916,33.69489714,28.60777933,33.52657313,34.31073157,29.58385187,38.22825781,28.52808176,30.32543453,28.99600065,33.58929394,33.55661531,31.80350676,27.51758858,26.42679052,22.56882719,29.40501985,27.11865431,31.2194901,25.02033525,32.56188419,23.80603502,23.25368036,36.69392594,24.30598942,27.11667459,21.70827545,22.71821439,24.5629347,32.74370888,24.02615372,27.35939135,30.31811492,25.35655028,40.93464984,27.12076543,27.34223081,36.00449118,26.18075353,28.25536108,19.2136474,37.79199114,33.90611589,32.39938729,25.56636738,29.87357789,27.9097813,30.84157406,26.52593714,31.96754454,31.6869999,28.51033264,36.3892931,31.4343278,31.39032768],[2,2,2,1,1,1,1,2,1,2,1,2,2,2,2,2,2,2,2,1,2,1,1,2,2,2,1,2,2,1,1,1,2,2,1,2,1,1,1,1,2,2,1,1,1,2,2,1,2,2,1,1,2,1,2,2,1,2,1,2,1,2,2,2,2,1,1,1,2,1,1,2,1,2,2,1,1,1,1,2,1,1,1,1,2,2,2,1,2,2,1,2,2,1,2,2,1,2,1,2,2,1,2,1,2,1,1,2,1,1,1,1,2,2,1,2,1,1,2,1,2,2,1,1,1,1,1,2,2,1,1,2,2,1,2,2,2,2,1,2,1,2,2,1,2,1,2,2,1,1,1,1,1,1,1,1,2,1,1,1,2,1,1,2,2,2,2,2,2,2,2,1,2,1,2,2,2,1,2,1,1,2,1,1,2,2,2,1,1,2,1,2,2,1,2,2,1,2,1,1,2,1,1,2,1,1,1,1,1,1,1,2,1,1,2,1,2,2,1,2,1,2,1,2,2,2,2,2,1,1,2,1,2,1,1,2,2,2,2,1,2,2,2,1,1,1,1,2,2,2,2,1,2,2,1,1,1,1,1,1,1,1,1,2,2,2,2,1,1,2,2,1,1,1,2,1,2,1,1,2,1,1,2,1,2,1,1,1,2,2,1,2,2,2,2,1,1,1,1,2,2,1,1,1,1,2,2,2,1,2,2,2,2,1,2,2,2,1,2,1,2,1,2,2,2,1,2,1,1,2,1,1,1,1,1,2,1,2,1,1,1,1,1,1,2,1,1,2,1,1,1,2,2,2,2,1,2,1,1,1,1,2,2,2,1,1,2,1,1,2,2,1,2,2,2,2,2,1,1,2,1,2,2,2,1,1,2,2,2,2,2,2,2,1,1,2,2,1,2,2,1,1,1,1,1,1,2,1,2,2,1,2,2,1,1,1,2,1,1,1,1,2,1,1,1,1,2,2,1,1,1,2,2,1,2,1,1,2,2,1,1,1,1,1,1,1,2,1,1,1,2,2,1,1,2,1,1,1,1,2,1,1,1,1,2,2,2,1,2,2,1,2,2,1,1,1,2,2,1,2,2,1,2,1,2,1,2,1,1,2,2,2,1,1,2,2,2,2,2,2,2,2,1,2,1,1,1,2,2,2,1,1,1,1,2,2,2,1,1,1,2,2,2,1,2,2,1,1,2,1,2,2,2,1,2,1,1,1,2,2,1,1,1,2,1,1,2,2,1,1,1,2,2,1,1,2,1,2,1,1,2,2,2,1,2,2,2,1,2,2,1,1,2,1,2,2,1,1,1,2,2,2,2,2,1,2,2,2,1,1,2,2,1,2,1,1,1,1,2,1],[2,2,2,3,2,1,2,1,2,1,1,3,3,3,3,3,2,2,3,2,3,1,2,3,3,2,2,2,1,1,2,3,3,2,1,1,2,2,1,2,1,3,2,1,3,2,2,2,3,2,2,2,3,2,2,2,1,1,3,2,2,3,1,3,1,2,3,1,3,3,3,2,2,1,1,1,3,1,1,3,2,1,3,2,2,1,1,3,3,2,2,2,3,2,3,2,3,2,2,3,3,3,2,3,2,2,1,1,3,2,2,3,1,3,1,3,3,3,1,1,2,3,1,1,1,3,2,2,3,1,3,2,2,3,2,3,1,1,1,3,3,3,3,3,3,3,2,2,1,1,3,1,1,1,1,1,1,2,2,2,1,3,3,3,1,1,2,1,2,2,3,3,2,2,1,2,2,1,3,2,3,2,1,1,2,2,3,1,3,1,2,3,1,3,3,3,3,3,3,2,1,3,3,2,2,2,3,1,3,3,3,3,3,3,2,3,2,3,3,1,3,3,3,2,3,1,3,2,3,3,3,2,3,3,2,2,2,2,1,2,1,2,2,3,3,3,2,1,3,3,3,3,1,1,2,2,3,2,3,2,2,2,3,1,2,1,3,3,2,2,1,1,1,3,1,2,2,1,1,2,1,1,3,3,2,2,2,3,1,1,2,2,3,1,1,3,1,2,2,1,2,3,3,3,1,3,3,3,2,2,3,3,3,3,3,1,3,1,1,3,3,2,2,2,3,1,1,1,1,1,3,2,2,3,1,2,1,1,3,3,1,1,3,2,1,1,2,1,2,2,2,3,1,1,1,2,3,3,3,3,2,1,3,3,3,2,1,1,2,1,1,2,3,3,3,1,1,1,1,2,3,2,3,3,3,1,1,2,3,1,1,1,1,2,2,1,3,3,1,1,1,2,2,2,2,1,2,3,1,1,1,2,2,1,3,2,1,2,2,2,2,1,1,1,3,3,1,1,3,3,1,1,3,3,2,2,1,1,2,2,1,2,1,3,1,1,1,1,1,1,3,3,2,1,1,3,3,2,2,1,2,3,1,2,1,3,2,1,2,1,3,1,1,1,1,3,1,3,1,2,2,1,3,2,1,1,1,3,1,1,2,3,2,1,1,1,1,1,2,1,1,2,3,2,1,3,2,1,2,2,3,2,1,2,3,2,3,1,1,3,2,3,1,1,3,2,3,2,1,1,1,2,2,2,1,1,1,1,1,3,1,2,2,3,1,1,2,1,2,3,3,3,1,2,3,2,1,3,1,3,3,3,3,2,2,1,3,1,1,2,3,3,2,1,2,1,1,1,1,2,3,3,2,2,2,1,2,3,3,3,1,2,3,1,2,2,3,3,3,1]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>weight_loss<\/th>\n      <th>hours<\/th>\n      <th>effort<\/th>\n      <th>gender<\/th>\n      <th>routine<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"pageLength":5,"columnDefs":[{"className":"dt-right","targets":[1,2,3,4,5]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false,"lengthMenu":[5,10,25,50,100]}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>The mathematical equation for the model is: <span class="math display">\[
\begin{align*}
Y_i &amp;= \beta_0 + \beta_1X_{i, 1} + \beta_2X_{i, 2} + \beta_3X_{i, 3} \\
&amp;\quad + \beta_4X_{i, 4}  + \beta_5X_{i, 5} + \epsilon_i, \quad i = 1, \dots, n
\end{align*}
\]</span></p>
<p>where:</p>
<ul>
<li>The <span class="math inline">\(\beta_i\)</span>s are the model parameters, the <span class="math inline">\(x_i\)</span>s are the explanatory variables, and the <span class="math inline">\(\epsilon_i\)</span>s are the errors for observations <span class="math inline">\(i\)</span>.</li>
</ul>
<p>In more detail, our predictions are given by: <span class="math display">\[
\begin{align*}
\hat{Y}_i &amp;= \hat{\beta}_0 + \hat{\beta}_1X_{i,1} + \hat{\beta}_2X_{i,2} + \hat{\beta}_3X_{i,3} \\
          &amp;\quad
+ \hat{\beta}_4X_{i,4} + \hat{\beta}_5X_{i,5}, \quad i = 1, \ldots, n
\end{align*}
\]</span></p>
<p>where:</p>
<ul>
<li><p><span class="math inline">\(\hat \beta_0\)</span> is the expected value of <span class="math inline">\(Y\)</span> when all the continuous predictors are 0 and the categorical predictor indicators <span class="math inline">\(X_3\)</span>, <span class="math inline">\(X_4\)</span>, <span class="math inline">\(X_5\)</span> are all 0 (i.e., all categorical predictors are in their reference categories).</p></li>
<li><p><span class="math inline">\(\hat \beta_1\)</span> is the expected change in <span class="math inline">\(Y\)</span> holding all other variables fixed and when <span class="math inline">\(X_1\)</span> (average hours spent exercising in a day) increases by one unit.</p></li>
<li><p><span class="math inline">\(\hat \beta_2\)</span> is the expected change in <span class="math inline">\(Y\)</span> holding all other variables fixed and when <span class="math inline">\(X_2\)</span> (amount of effort put into exercising) increases by one unit.</p></li>
<li><p><span class="math inline">\(\hat \beta_3\)</span> is the expected change in <span class="math inline">\(Y\)</span> holding all other variables fixed and when <span class="math inline">\(X_3\)</span> (gender) is switched from the reference category (1 - male) to the other category (2 - female).</p></li>
<li><p><span class="math inline">\(\hat \beta_4\)</span> is the expected change in <span class="math inline">\(Y\)</span> holding all other variables fixed and when <span class="math inline">\(X_4\)</span> (routine 2 indicator) is switched from the reference category (routine 1) to the second category (routine 2).</p></li>
<li><p><span class="math inline">\(\hat \beta_5\)</span> is the expected change in <span class="math inline">\(Y\)</span> holding all other variables fixed and when <span class="math inline">\(X_5\)</span> (routine 3 indicator) is switched from the reference category (routine 1) to the third category (routine 3).</p></li>
</ul>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">=</span> <span class="fu">lm</span>(weight_loss<span class="sc">~</span>hours<span class="sc">+</span>effort<span class="sc">+</span><span class="fu">factor</span>(gender)<span class="sc">+</span><span class="fu">factor</span>(routine), </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data=</span>df)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = weight_loss ~ hours + effort + factor(gender) + 
    factor(routine), data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-16.6243  -4.6222  -0.0022   4.4040  18.4742 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      -19.36311    1.83066 -10.577  &lt; 2e-16 ***
hours              3.29536    0.53097   6.206 1.02e-09 ***
effort             0.68967    0.04938  13.966  &lt; 2e-16 ***
factor(gender)2    0.05610    0.51158   0.110    0.913    
factor(routine)2  18.36189    0.62869  29.207  &lt; 2e-16 ***
factor(routine)3 -11.42231    0.62332 -18.325  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.26 on 594 degrees of freedom
Multiple R-squared:  0.8154,    Adjusted R-squared:  0.8139 
F-statistic: 524.9 on 5 and 594 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="interpret-the-estimates-of-the-parameters" class="level2">
<h2 class="anchored" data-anchor-id="interpret-the-estimates-of-the-parameters">Interpret the Estimates of the Parameters</h2>
<ul>
<li><p>As described above, <span class="math inline">\(\hat \beta_0\)</span> is the expected value of <span class="math inline">\(Y\)</span> when all the continuous predictors are 0 and the categorical predictor indicators <span class="math inline">\(X_3\)</span>, <span class="math inline">\(X_4\)</span>, <span class="math inline">\(X_5\)</span> are all 0 (i.e., all categorical predictors are in their reference categories).</p>
<ul>
<li>In other words, if we had an observation who was male, did routine 1, averaged 0 hours of exercise a day, and put in 0 (minimal) effort into exercising, their predicted weight loss would be equal to the intercept of -19.36311. (i.e., an increase in weight)</li>
</ul></li>
<li><p>As described above, <span class="math inline">\(\hat \beta_1\)</span> is the expected change in <span class="math inline">\(Y\)</span> holding all other variables fixed and when <span class="math inline">\(X_1\)</span> (average hours spent exercising in a day) increases by one unit.</p>
<ul>
<li>Hence for a unit increase in average hours spent exercising in a day, we expect a person’s weight loss to increase by 3.29.</li>
</ul></li>
<li><p>As described above, <span class="math inline">\(\hat \beta_2\)</span> is the expected change in <span class="math inline">\(Y\)</span> holding all other variables fixed and when <span class="math inline">\(X_2\)</span> (amount of effort put into exercising) increases by one unit.</p>
<ul>
<li>Hence for a unit increase in the amount of physical effort put into exercising, we expect a person’s weight loss to increase by 0.68967.</li>
</ul></li>
<li><p>As described above, <span class="math inline">\(\hat \beta_3\)</span> is the expected change in <span class="math inline">\(Y\)</span> holding all other variables fixed and when <span class="math inline">\(X_3\)</span> (gender) is switched from the reference category (1 - male) to the other category (2 - female).</p>
<ul>
<li>So if we had two observations with all predictors being equal, but with the only difference between them being gender - we would predict the female’s weight loss to be 0.0561 greater than the male.</li>
</ul></li>
<li><p>As described above, <span class="math inline">\(\hat \beta_4\)</span> is the expected change in <span class="math inline">\(Y\)</span> holding all other variables fixed and when <span class="math inline">\(X_4\)</span> (routine 2 indicator) is switched from the reference category (routine 1) to the second category (routine 2). In this case, the value of <span class="math inline">\(X_4\)</span> would change from 0 to 1.</p>
<ul>
<li>So if we had two observations with all predictors being equal, but with the only difference between them being that one did exercise routine 2 and the other did routine 1 - we would predict the individual who did routine 2 to have an additional weight loss of 18.36.</li>
</ul></li>
<li><p>As described above, <span class="math inline">\(\hat \beta_5\)</span> is the expected change in <span class="math inline">\(Y\)</span> holding all other variables fixed and when <span class="math inline">\(X_5\)</span> (routine 3 indicator) is switched from the reference category (routine 1) to the third category (routine 3). In this case, the value of <span class="math inline">\(X_5\)</span> would change from 0 to 1.</p>
<ul>
<li>So if we had two observations with all predictors being equal, but with the only difference between them being that one did exercise routine 3 and the other did routine 1 - we would predict the individual who did routine 3 to have a reduction in weight loss of -11.42.</li>
</ul></li>
</ul>
</section>
<section id="which-values-of-the-categorical-predictor-variables-will-lead-to-the-largest-reduction-in-weight" class="level2">
<h2 class="anchored" data-anchor-id="which-values-of-the-categorical-predictor-variables-will-lead-to-the-largest-reduction-in-weight">Which values of the categorical predictor variables will lead to the largest reduction in weight?</h2>
<p>From our summary output, we can see that:</p>
<ul>
<li><p>When the categorical variable <em>gender</em> is 2 (female), there is an increase in weight loss of 0.056. This is a minor difference.</p></li>
<li><p>When the categorical variable <em>routine</em> is 2 (so exercise routine 2), there is an increase in weight loss of 18.36. This is a large difference compared to both the reference routine (routine 1) and routine 3 (which leads to a <em>reduction in weight loss</em> of -11.42).</p></li>
</ul>
<p>So the combination of gender being <em>female</em> and routine being <em>2</em> will lead to the largest reduction in weight.</p>
</section>
<section id="the-effect-and-significance-of-the-categorical-variable-routine-in-our-model." class="level2">
<h2 class="anchored" data-anchor-id="the-effect-and-significance-of-the-categorical-variable-routine-in-our-model.">The effect and significance of the categorical variable <strong>routine</strong> in our model.</h2>
<p>In the above, we noted that:</p>
<ul>
<li><p>When the categorical variable <em>routine</em> is 2 (so exercise routine 2), there is an increase in weight loss of 18.36 holding all other variables constant.</p></li>
<li><p>Routine 3 leads to a <em>reduction in weight loss</em> of 11.42, holding all other variables constant.</p>
<ul>
<li><p>Both routine 2 and routine 3 have high significance levels which are less that <span class="math inline">\(2e-16\)</span>. These are far below the typical significance level of 0.05.</p></li>
<li><p>This is in contrast to gender which we can see has a significance level of 0.913.</p></li>
</ul></li>
</ul>
<p>Hence we can say that routine has a very strong effect in the model given the low p-values and high coefficient values.</p>
</section>
<section id="hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing">Hypothesis Testing</h2>
<section id="interpreting-the-f-statistic" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-the-f-statistic">Interpreting the F-statistic</h3>
<p>The F statistic output is given as 524.9 on 5 and 594 DF, p-value: &lt; 2.2e-16.</p>
<p>This is testing a reduced model: <span class="math display">\[
Y =  \beta_0
\]</span> against the full model: <span class="math display">\[
Y =  \beta_0 +  \beta_1X_{1} +  \beta_2X_{2} +  \beta_3X_{3} +   \beta_4X_{4} +   \beta_5X_{5}
\]</span></p>
<p>The null hypothesis is: <span class="math display">\[
H_0:  \beta_1 =  \beta_2 =  \beta_3 =  \beta_4 =  \beta_5 = 0
\]</span> And the alternative hypothesis is: <span class="math display">\[
H_1: \text{at least one of }  \beta_1, ...,  \beta_5 \neq 0.
\]</span> The F-statistic for this is found to be <span class="math inline">\(F = 524.9\)</span>, and the p-value on 5 and 594 degrees of freedom <span class="math inline">\(P(F&gt;524.9)\)</span> is less than <span class="math inline">\(2.2e-16.\)</span></p>
<p>We can see that this rounds to 0 when we find it below:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>F <span class="ot">=</span> <span class="fl">524.9</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">pf</span>(F, <span class="dv">5</span>, <span class="dv">594</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>Therefore we reject the null hypothesis and find that at least one of the predictor variables <span class="math inline">\(\beta_1, ..., \beta_5\)</span> (i.e., hours, effort, gender, routine) is non-zero.</p>
</section>
<section id="testing-the-hypothesis-h_0-beta_1-beta_2-0" class="level3">
<h3 class="anchored" data-anchor-id="testing-the-hypothesis-h_0-beta_1-beta_2-0">Testing the hypothesis <span class="math inline">\(H_0: \beta_1 = \beta_2 = 0\)</span></h3>
<p>In order to test this hypothesis we will use the output of a type 2 ANOVA.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(fit, <span class="at">type=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type II tests)

Response: weight_loss
                Sum Sq  Df  F value    Pr(&gt;F)    
hours             1510   1   38.519 1.018e-09 ***
effort            7644   1  195.046 &lt; 2.2e-16 ***
factor(gender)       0   1    0.012    0.9127    
factor(routine)  88038   2 1123.182 &lt; 2.2e-16 ***
Residuals        23280 594                       
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Now we will calculate the F statistic:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>numerator <span class="ot">=</span> (<span class="dv">1510</span><span class="sc">+</span><span class="dv">7644</span>)<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>denominator <span class="ot">=</span> <span class="dv">23280</span><span class="sc">/</span><span class="dv">594</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>F_test <span class="ot">=</span> numerator <span class="sc">/</span> denominator</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co"># note there are 2 params - so we use 2 df</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>F_crit <span class="ot">=</span> <span class="fu">qf</span>(<span class="fl">0.05</span>, <span class="dv">2</span>, <span class="dv">594</span>,<span class="at">lower.tail =</span> <span class="dv">0</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"F test statistic:"</span>);<span class="fu">print</span>(F_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "F test statistic:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 116.7843</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"F critical:"</span>);<span class="fu">print</span>(F_crit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "F critical:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.010892</code></pre>
</div>
</div>
<p>We find that our test stat <span class="math inline">\(F=116.78 &gt; F_{0.05, 2, 594} = 3.01\)</span>.</p>
<p>Hence we reject the null hypothesis that the coefficients for the variables <em>hours</em> and <em>effort</em> are equal to 0 given that the categorical predictors <em>gender</em> and <em>routine</em> are in the model.</p>
</section>
</section>
<section id="interpreting-the-adjusted-r-squared-value" class="level2">
<h2 class="anchored" data-anchor-id="interpreting-the-adjusted-r-squared-value">Interpreting the Adjusted R-squared Value</h2>
<p>The adjusted R-squared value from the summary output is 0.8139. This adjusted R-squared value indicates that <em>approximately</em> 81.39% of the variability in the dependent variable is accounted for by the model, after adjusting for the number of predictors. This is a high value, suggesting that the model fits the data well.</p>
<p>The adjusted R-squared value adjusts adjusts multiple R-squared by dividing each sum of squares by its associated degrees of freedom. Differences include:</p>
<ul>
<li><p><span class="math inline">\(R^2_a\)</span> can be negative and only increases if the variation in Y accounted for by the added predictor is greater than the penalty.</p></li>
<li><p>In contrast, <span class="math inline">\(R^2\)</span> is always between 0 and 1 and can only become larger as more explanatory variables are added to the model.</p></li>
</ul>
<p>These differences are more clear when we look at the equations: <span class="math display">\[
R^2 = 1 - \frac{SSE}{SST}
\]</span> <span class="math display">\[
R^2_a = 1 - \frac{\frac{SSE}{n-p}}{\frac{SST}{n-1}}
\]</span></p>
</section>
<section id="predicting-weight-loss" class="level2">
<h2 class="anchored" data-anchor-id="predicting-weight-loss">Predicting Weight Loss</h2>
<p>How much loss would we predict for a male person, exercising 3 hours a day under routine number 2 with an effort of 25?</p>
<p>The predicted weight loss would be given by:</p>
<p><span class="math display">\[
\begin{align*}
\text{Predicted Weight Loss} &amp;= -19.36 \\
                             &amp;\quad + 3.29(\text{hours}) \\
                             &amp;\quad + 0.69(\text{effort}) \\
                             &amp;\quad + 0.06(\text{gender2}) \\
                             &amp;\quad + 18.36(\text{routine2}) \\
                             &amp;\quad - 11.42(\text{routine3})
\end{align*}
\]</span></p>
<p>Substituting in the values: <span class="math display">\[
\begin{align*}
\text{Predicted Weight Loss} &amp;= -19.36 \\
                             &amp;\quad + 3.29 \times 3 \\
                             &amp;\quad + 0.69 \times 25 \\
                             &amp;\quad + 0.06 \times 0 \\
                             &amp;\quad + 18.36 \times 1 \\
                             &amp;\quad - 11.42 \times 0 \\
                             &amp;= 26.12
\end{align*}
\]</span></p>
<p>Which we can also find through R:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>predicted_loss <span class="ot">=</span> fit<span class="sc">$</span>coefficients[<span class="dv">1</span>] <span class="sc">+</span> <span class="dv">3</span><span class="sc">*</span>fit<span class="sc">$</span>coefficients[<span class="dv">2</span>] <span class="sc">+</span> <span class="dv">25</span><span class="sc">*</span>fit<span class="sc">$</span>coefficients[<span class="dv">3</span>] <span class="sc">+</span> <span class="dv">0</span><span class="sc">*</span>fit<span class="sc">$</span>coefficients[<span class="dv">4</span>] <span class="sc">+</span> <span class="dv">1</span><span class="sc">*</span>fit<span class="sc">$</span>coefficients[<span class="dv">5</span>] <span class="sc">+</span> <span class="dv">0</span><span class="sc">*</span>fit<span class="sc">$</span>coefficients[<span class="dv">6</span>]</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(predicted_loss)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   26.12656 </code></pre>
</div>
</div>
<p>Therefore we would predict a weight loss of 26.12.</p>
<section id="prediction-interval-for-predicted-weight-loss" class="level3">
<h3 class="anchored" data-anchor-id="prediction-interval-for-predicted-weight-loss">95% Prediction Interval for Predicted Weight Loss</h3>
<p>We find the values of the 95% prediction interval for this individual using the R code below:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">hours=</span><span class="dv">3</span>, <span class="at">effort=</span><span class="dv">25</span>, </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">gender=</span><span class="fu">factor</span>(<span class="st">"1"</span>, <span class="at">levels=</span><span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"2"</span>)), </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">routine=</span><span class="fu">factor</span>(<span class="st">"2"</span>, <span class="at">levels=</span><span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"2"</span>, <span class="st">"3"</span>)))</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>prediction <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit, <span class="at">newdata=</span>newdata, <span class="at">interval=</span><span class="st">"prediction"</span>, <span class="at">level=</span><span class="fl">0.95</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>prediction</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 26.12656 13.73026 38.52285</code></pre>
</div>
</div>
<p>The prediction interval gives the range of values within which we expect the actual observed value to lie with 95% confidence, taking into account the error in the prediction. This interval is between 13.73 and 38.52.</p>
</section>
</section>
<section id="interaction-effects" class="level2">
<h2 class="anchored" data-anchor-id="interaction-effects">Interaction Effects</h2>
<p>Is there an interaction between the predictor variables effort and routine a person is enrolled in?</p>
<p>The below scatter plot matrix demonstrates that there are diverging lines (different slopes) - this indicates there is an interaction between these predictor variables.</p>
<p>We can fit a model to more rigorously test this hypothesis. Our proposed equation is:</p>
<p><span class="math display">\[
\begin{align*}
Y_i &amp;= \beta_0 + \beta_1X_{i, 1} + \beta_2X_{i,2} + \beta_3X_{i,3} + \beta_4X_{i,4} + \beta_5X_{i,5} \\
    &amp;\quad + \beta_6(X_{i,2} \times X_{i, 4}) + \beta_7(X_{i,2} \times X_{i, 5}) + \epsilon_i, \quad i = 1, ..., n
\end{align*}
\]</span></p>
<p>To make this more clear in terms of the predictors, we can also express it as:</p>
<p><span class="math display">\[
\begin{align*}
\text{Predicted Weight Loss} &amp;= \beta_0 + \beta_1(\text{hours}) + \beta_2(\text{effort}) + \beta_3(\text{gender2}) \\
                             &amp;\quad + \beta_4(\text{routine2}) + \beta_5(\text{routine3}) \\
                             &amp;\quad + \beta_6(\text{effort} \times \text{routine2}) + \beta_7(\text{effort} \times \text{routine3}),
\end{align*}
\]</span></p>
<p>where the interaction terms, <span class="math inline">\(\beta_6(\text{effort} \times \text{routine2})\)</span> and <span class="math inline">\(\beta_7(\text{effort} \times \text{routine3})\)</span>, capture the additional effect on the predicted weight loss that is due to the combination of effort with each level of routine beyond the <em>main effects</em> of routine and effort by themselves.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">scatterplotMatrix</span>(<span class="sc">~</span>effort <span class="sc">+</span> weight_loss <span class="sc">|</span><span class="fu">factor</span>(routine),<span class="at">data=</span>df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="mlr_weight_loss_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="modelling-the-interaction" class="level3">
<h3 class="anchored" data-anchor-id="modelling-the-interaction">Modelling the Interaction</h3>
<p>In our new model with interaction added, we observe that the fit has improved as the <em>adjusted</em> R-squared value has increased from 0.8139 to 0.845.</p>
<p>We can also observe that the interactions between effort and routines 2 and 3 have extremely low p-values, indicating their importance to the model.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">=</span> <span class="fu">lm</span>(weight_loss<span class="sc">~</span>hours<span class="sc">+</span>effort<span class="sc">+</span><span class="fu">factor</span>(gender)<span class="sc">+</span><span class="fu">factor</span>(routine) <span class="sc">+</span> effort<span class="sc">*</span><span class="fu">factor</span>(routine), </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">data=</span>df)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = weight_loss ~ hours + effort + factor(gender) + 
    factor(routine) + effort * factor(routine), data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-16.9171  -4.2410   0.4682   4.3224  14.0335 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)             -21.20932    2.52277  -8.407 3.14e-16 ***
hours                     3.39338    0.48550   6.989 7.46e-12 ***
effort                    0.74513    0.07919   9.409  &lt; 2e-16 ***
factor(gender)2           0.05419    0.46700   0.116  0.90766    
factor(routine)2          2.91063    3.36613   0.865  0.38756    
factor(routine)3          8.77053    3.31974   2.642  0.00846 ** 
effort:factor(routine)2   0.50847    0.11036   4.608 4.99e-06 ***
effort:factor(routine)3  -0.69389    0.11110  -6.246 8.06e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.713 on 592 degrees of freedom
Multiple R-squared:  0.8468,    Adjusted R-squared:  0.845 
F-statistic: 467.5 on 7 and 592 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="diagnostic-tests-on-the-regression-model" class="level1">
<h1>Diagnostic tests on the regression model</h1>
<section id="linearity-assumption" class="level2">
<h2 class="anchored" data-anchor-id="linearity-assumption">Linearity Assumption</h2>
<p>The consequences of the model not satisfying the linearity assumption are that it will lead to biased and inconsistent estimates.</p>
<p>We can check the linearity assumption of our model by using scatterplots, added variable plots, and component-plus-residual plots.</p>
<section id="scatterplots" class="level3">
<h3 class="anchored" data-anchor-id="scatterplots">Scatterplots</h3>
<p>Examining the scatterplots first we see that we could fit a line through the scatterplots for our continuous predictors against weight_loss. However, we can see that there would be a lot of points far away from this line and hence we will investigate this further. In addition, we note that the weight_loss distribution is right-skewed.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="mlr_weight_loss_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="added-variable-plots" class="level3">
<h3 class="anchored" data-anchor-id="added-variable-plots">Added Variable Plots</h3>
<p>Now examining added-variable plots, we see that the lines generally fit the scatterplot well despite some outliers for our continuous predictors ‘hours’ and ‘effort’. The straight lines and the lack of a pattern we observe in the scattering of the points around the line are a good sign that the model satisfies the linearity assumption.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">avPlots</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="mlr_weight_loss_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We do not check the component-plus-residual plots as they are not available for models with interactions.</p>
<p>In conclusion, we can say that the model seems to satisfy the linearity assumption based on our observation of the scatterplot matrix and added-variable plots.</p>
</section>
</section>
<section id="added-variable-plots-in-detail" class="level2">
<h2 class="anchored" data-anchor-id="added-variable-plots-in-detail">Added Variable Plots in Detail</h2>
<p>We used an added variable plot in the previous question to test the linearity assumption.</p>
<p>To elaborate further, it provides a way to visualise the relationship between the dependent variable (weight_loss) and one of the independent variables (hours, say) while controlling for the presence of the other independent variables in the model.</p>
<p>Through this it can show us whether the relationship between the independent variable and dependent variable is linear when the effects of the other variables are removed. In addition, it helps us identify outliers and influential observations.</p>
<section id="interpretations-for-all-predictor-variables-in-the-model" class="level3">
<h3 class="anchored" data-anchor-id="interpretations-for-all-predictor-variables-in-the-model">Interpretations for all predictor variables in the model</h3>
<p>Hours</p>
<ul>
<li>The added variable plot for hours shows a linear relationship with the dependent variable weight_loss. The slope is positive, suggesting that once the other variables are accounted for, hours is a strong predictor. The points are scattered roughly evenly about the line despite some outliers.</li>
</ul>
<p>Effort</p>
<ul>
<li>The added variable plot for effort shows a linear relationship with the dependent variable weight_loss. The slope is greater than the slope for hours, suggesting that once the other variables are accounted for, effort is a very strong predictor. There is a notable concentration of the points around 0.</li>
</ul>
<p>Gender</p>
<ul>
<li>The plot for the categorical variable gender shows a flat regression line, which implies that there is no significant linear relationship between gender and weight_loss once the other variables are accounted for. This agrees with high p-value in the summary output of our model.</li>
</ul>
<p>Routine</p>
<ul>
<li><p>The plots for the categorical variable routine differ between routine2 and routine3. Routine2 has an almost flat line indicating that there is no significant linear relationship between this routine and weight_loss - this also agrees with the high p-value for this predictor in the summary output. In contrast, routine3 has a more positive slope which indicates a stronger linear relationship with weight_loss. Again, this agrees with the low p-value in the summary output.</p></li>
<li><p>In both of these plots there is a concentration of points around 0.</p></li>
</ul>
<p>Interaction between effort and routine</p>
<ul>
<li><p>The interaction plots show that the linear relationship between effort and weight_loss changes with the different levels of the categorical variable routine.</p>
<ul>
<li><p>Effort*routine2 shows a slight positive linear relationship with weight loss once the other variables are accounted for. The points are mostly scattered evenly around the line with a concentration around 0.</p></li>
<li><p>Effort*routine3 shows a stronger negative linear relationship with weight loss once the other variables are accounted for. The points are mostly scattered evenly around the line with a concentration around 0.</p></li>
</ul></li>
</ul>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">avPlots</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="mlr_weight_loss_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
</section>
<section id="anova" class="level1">
<h1>ANOVA</h1>
<section id="anova-type-i" class="level2">
<h2 class="anchored" data-anchor-id="anova-type-i">ANOVA Type I</h2>
<p>R’s default ANOVA function is a Type 1 ANOVA. This anova function behaves in a cumulative way - sequentially adding each predictor.</p>
<p>For each predictor, the null hypothesis <span class="math inline">\(H_0\)</span> is that the predictor does not explain a significant amount of variance in the response variable weight_loss. The alternative hypothesis <span class="math inline">\(H_1\)</span> is that the predictor does not explain a significant amount of variance.</p>
<p>To illustrate this consider the following:</p>
<ul>
<li><p>The hours line:</p>
<ul>
<li>Compares <span class="math inline">\(\hat{Y} = \hat{\beta_0}\)</span> to <span class="math inline">\(\hat{Y} = \hat{\beta_0} + \hat{\beta_1}hours\)</span>. The variation (sum of squares) in Y that is explained by including hours given that no other variables are in the model is 892. The <strong>test statistic</strong> F is 27.33 and the <strong>p-value</strong> is 2.383e-07. Based on this low p-value we reject the null hypothesis and <strong>conclude</strong> that ‘hours’ significantly explains variance in ‘weight_loss.’</li>
</ul></li>
<li><p>The effort line:</p>
<ul>
<li>Compares <span class="math inline">\(\hat{Y} = \hat{\beta_0} + \hat{\beta_1}hours\)</span> to <span class="math inline">\(\hat{Y} = \hat{\beta_0} + \hat{\beta_1}hours + \hat{\beta_2} effort\)</span>. The variation (sum of squares) in Y that is explained by including effort given that hours is already in the model is 13922 The <strong>test statistic</strong> F is 426.53 and the <strong>p-value</strong> is less than 2.2e-16. Based on this low p-value we reject the null hypothesis and conclude that ‘effort’ significantly explains variance in ‘weight_loss,’ given than hours is already in the model.</li>
</ul></li>
</ul>
<p>We can extend this explanation trivially to the remaining predictors, but I will not include this for the sake of brevity.</p>
<p>Finally, we note that the residuals represent the variation in weight_loss that is not explained by the model. The lower the residual mean square (33), the better the model explains the data.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: weight_loss
                        Df Sum Sq Mean Sq   F value    Pr(&gt;F)    
hours                    1    892     892   27.3292 2.383e-07 ***
effort                   1  13922   13922  426.5275 &lt; 2.2e-16 ***
factor(gender)           1      0       0    0.0037    0.9512    
factor(routine)          2  88038   44019 1348.6538 &lt; 2.2e-16 ***
effort:factor(routine)   2   3957    1979   60.6209 &lt; 2.2e-16 ***
Residuals              592  19322      33                        
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="anova-type-ii" class="level2">
<h2 class="anchored" data-anchor-id="anova-type-ii">ANOVA Type II</h2>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(fit, <span class="at">type=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type II tests)

Response: weight_loss
                       Sum Sq  Df   F value    Pr(&gt;F)    
hours                    1595   1   48.8524 7.463e-12 ***
effort                   7644   1  234.2008 &lt; 2.2e-16 ***
factor(gender)              0   1    0.0135    0.9077    
factor(routine)         88038   2 1348.6538 &lt; 2.2e-16 ***
effort:factor(routine)   3957   2   60.6209 &lt; 2.2e-16 ***
Residuals               19322 592                        
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>In comparison, Type 2 ANOVA does not work in a cumulative and additive way as with the Type 1 Anova table. Instead, each row begins with the full fitted model and then compares it with a model without one of the predictor variables.</p>
<p>Therefore, the hours line compares the residuals of: <span class="math display">\[
\begin{align*}
\text{Predicted Weight Loss} &amp;= \beta_0 + \beta_1(\text{hours}) + \beta_2(\text{effort}) + \beta_3(\text{gender2}) \\
  &amp;\quad + \beta_4(\text{routine2}) + \beta_5(\text{routine3}) \\
  &amp;\quad + \beta_6(\text{effort} \times \text{routine2}) + \beta_7(\text{effort} \times \text{routine3})
\end{align*}
\]</span></p>
<p>to the residuals of: <span class="math display">\[
\begin{align*}
\text{Predicted Weight Loss} &amp;= \beta_0 + \beta_2(\text{effort}) + \beta_3(\text{gender2}) \\
  &amp;\quad + \beta_4(\text{routine2}) + \beta_5(\text{routine3}) \\
  &amp;\quad + \beta_6(\text{effort} \times \text{routine2}) + \beta_7(\text{effort} \times \text{routine3})
\end{align*}
\]</span></p>
<p>(note these should be <span class="math inline">\(\hat\beta\)</span>s). If there is a significant reduction in residuals when hours is included, then that term should remain in the model.</p>
<ul>
<li>In the case of hours then, the variation in weight_loss explained when this predictor is added into the full model is 1595 (note this is higher than in the case of the Type 1 ANOVA). The F statistic is 48.85 and the p-value is 7.463e-12. Therefore we reject the null hypothesis and conclude that this term should remain in the model.</li>
</ul>
<p>Again, we can extend this explanation trivially to the remaining predictors, but I will not include this for the sake of brevity.</p>
<p>We can calculate the test statistic for hours manually from the output below (note there is some minor rounding error):</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>numerator <span class="ot">=</span> <span class="dv">1595</span> <span class="sc">/</span> <span class="dv">1</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>denominator <span class="ot">=</span> <span class="dv">19322</span> <span class="sc">/</span> <span class="dv">592</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>F_test <span class="ot">=</span> numerator <span class="sc">/</span> denominator</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>F_crit <span class="ot">=</span> <span class="fu">qf</span>(<span class="fl">0.05</span>, <span class="dv">1</span>, <span class="dv">592</span>,<span class="at">lower.tail =</span> <span class="dv">0</span>)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"F test statistic:"</span>);<span class="fu">print</span>(F_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "F test statistic:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 48.86865</code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"F critical:"</span>);<span class="fu">print</span>(F_crit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "F critical:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.857215</code></pre>
</div>
</div>
<p>And we can also calculate the adjust R-squared value using:</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>SSR <span class="ot">=</span> <span class="dv">1595</span> <span class="sc">+</span> <span class="dv">7644</span> <span class="sc">+</span> <span class="dv">88038</span> <span class="sc">+</span> <span class="dv">3957</span> </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>SST <span class="ot">=</span> SSR <span class="sc">+</span> <span class="dv">19322</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>SSE <span class="ot">=</span> <span class="dv">19322</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="co"># equivalent</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>R2 <span class="ot">=</span> SSR<span class="sc">/</span>SST</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>R2 <span class="ot">=</span> <span class="dv">1</span> <span class="sc">-</span> SSE<span class="sc">/</span>SST</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="co"># adjusted R squared - note the dfs for SSE (n-p) and SST (n-1)</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>R2a <span class="ot">=</span> <span class="dv">1</span> <span class="sc">-</span> (SSE<span class="sc">/</span>(<span class="dv">592</span>)) <span class="sc">/</span> (SST<span class="sc">/</span><span class="dv">599</span>)</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(R2a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8378308</code></pre>
</div>
</div>
<!-- -->

</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb36" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "MLR - Weight Loss Data"</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span><span class="co"> html</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># add toc to html</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="an">toc:</span><span class="co"> true</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="an">toc-location:</span><span class="co"> left</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="an">code-fold:</span><span class="co"> show</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a><span class="an">code-tools:</span><span class="co"> true # add code tools to html </span></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a><span class="co"># add author and date</span></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Enda Flynn"</span></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2024-07-29"</span></span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a><span class="an">theme:</span></span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a><span class="co">  light: cosmo</span></span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a><span class="co">  dark: darkly</span></span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a>_Note that you can collapse the code using the button on the top right to focus on the analysis._</span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-21"><a href="#cb36-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-22"><a href="#cb36-22" aria-hidden="true" tabindex="-1"></a><span class="fu"># Introduction</span></span>
<span id="cb36-23"><a href="#cb36-23" aria-hidden="true" tabindex="-1"></a>This analysis will focus on applying multiple linear regression to the weight loss data set. </span>
<span id="cb36-24"><a href="#cb36-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-25"><a href="#cb36-25" aria-hidden="true" tabindex="-1"></a>In this analysis, we will cover:</span>
<span id="cb36-26"><a href="#cb36-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-27"><a href="#cb36-27" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Fitting a multiple linear regression model to the data</span>
<span id="cb36-28"><a href="#cb36-28" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Interpreting the estimates for the continuous and categorical predictors in the model</span>
<span id="cb36-29"><a href="#cb36-29" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Model diagnostics with scatterplots and added variable plots</span>
<span id="cb36-30"><a href="#cb36-30" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Type 1 and Type 2 ANOVA tests</span>
<span id="cb36-31"><a href="#cb36-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-32"><a href="#cb36-32" aria-hidden="true" tabindex="-1"></a><span class="fu"># Multiple Regression Model</span></span>
<span id="cb36-33"><a href="#cb36-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-34"><a href="#cb36-34" aria-hidden="true" tabindex="-1"></a><span class="fu">## Model Specification</span></span>
<span id="cb36-35"><a href="#cb36-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-36"><a href="#cb36-36" aria-hidden="true" tabindex="-1"></a>We begin by loading the necessary libraries and the data set - we can explore this interactively in the table below to get a sense of the </span>
<span id="cb36-39"><a href="#cb36-39" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb36-40"><a href="#cb36-40" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: true</span></span>
<span id="cb36-41"><a href="#cb36-41" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb36-42"><a href="#cb36-42" aria-hidden="true" tabindex="-1"></a><span class="co">#| output: false  </span></span>
<span id="cb36-43"><a href="#cb36-43" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb36-44"><a href="#cb36-44" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb36-45"><a href="#cb36-45" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb36-46"><a href="#cb36-46" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DT) </span>
<span id="cb36-47"><a href="#cb36-47" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb36-48"><a href="#cb36-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-51"><a href="#cb36-51" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb36-52"><a href="#cb36-52" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"data/weight_loss.csv"</span>)</span>
<span id="cb36-53"><a href="#cb36-53" aria-hidden="true" tabindex="-1"></a><span class="fu">datatable</span>(df, <span class="at">options =</span> <span class="fu">list</span>(<span class="at">pageLength =</span> <span class="dv">5</span>))</span>
<span id="cb36-54"><a href="#cb36-54" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb36-55"><a href="#cb36-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-56"><a href="#cb36-56" aria-hidden="true" tabindex="-1"></a>The mathematical equation for the model is: </span>
<span id="cb36-57"><a href="#cb36-57" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb36-58"><a href="#cb36-58" aria-hidden="true" tabindex="-1"></a>\begin{align*}</span>
<span id="cb36-59"><a href="#cb36-59" aria-hidden="true" tabindex="-1"></a>Y_i &amp;= \beta_0 + \beta_1X_{i, 1} + \beta_2X_{i, 2} + \beta_3X_{i, 3} <span class="sc">\\</span></span>
<span id="cb36-60"><a href="#cb36-60" aria-hidden="true" tabindex="-1"></a>&amp;\quad + \beta_4X_{i, 4}  + \beta_5X_{i, 5} + \epsilon_i, \quad i = 1, \dots, n</span>
<span id="cb36-61"><a href="#cb36-61" aria-hidden="true" tabindex="-1"></a>\end{align*}</span>
<span id="cb36-62"><a href="#cb36-62" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb36-63"><a href="#cb36-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-64"><a href="#cb36-64" aria-hidden="true" tabindex="-1"></a>where:</span>
<span id="cb36-65"><a href="#cb36-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-66"><a href="#cb36-66" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The $\beta_i$s are the model parameters, the $x_i$s are the explanatory variables, and the $\epsilon_i$s are the errors for observations $i$.</span>
<span id="cb36-67"><a href="#cb36-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-68"><a href="#cb36-68" aria-hidden="true" tabindex="-1"></a>In more detail, our predictions are given by: </span>
<span id="cb36-69"><a href="#cb36-69" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb36-70"><a href="#cb36-70" aria-hidden="true" tabindex="-1"></a>\begin{align*}</span>
<span id="cb36-71"><a href="#cb36-71" aria-hidden="true" tabindex="-1"></a>\hat{Y}_i &amp;= \hat{\beta}_0 + \hat{\beta}_1X_{i,1} + \hat{\beta}_2X_{i,2} + \hat{\beta}_3X_{i,3} <span class="sc">\\</span></span>
<span id="cb36-72"><a href="#cb36-72" aria-hidden="true" tabindex="-1"></a>          &amp;\quad</span>
<span id="cb36-73"><a href="#cb36-73" aria-hidden="true" tabindex="-1"></a><span class="ss">+ </span>\hat{\beta}_4X_{i,4} + \hat{\beta}_5X_{i,5}, \quad i = 1, \ldots, n</span>
<span id="cb36-74"><a href="#cb36-74" aria-hidden="true" tabindex="-1"></a>\end{align*}</span>
<span id="cb36-75"><a href="#cb36-75" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb36-76"><a href="#cb36-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-77"><a href="#cb36-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-78"><a href="#cb36-78" aria-hidden="true" tabindex="-1"></a>where:</span>
<span id="cb36-79"><a href="#cb36-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-80"><a href="#cb36-80" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>$\hat \beta_0$ is the expected value of $Y$ when all the continuous predictors are 0 and the categorical predictor indicators $X_3$, $X_4$, $X_5$ are all 0 (i.e., all categorical predictors are in their reference categories).</span>
<span id="cb36-81"><a href="#cb36-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-82"><a href="#cb36-82" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>$\hat \beta_1$ is the expected change in $Y$ holding all other variables fixed and when $X_1$ (average hours spent exercising in a day) increases by one unit.</span>
<span id="cb36-83"><a href="#cb36-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-84"><a href="#cb36-84" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>$\hat \beta_2$ is the expected change in $Y$ holding all other variables fixed and when $X_2$ (amount of effort put into exercising) increases by one unit.</span>
<span id="cb36-85"><a href="#cb36-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-86"><a href="#cb36-86" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>$\hat \beta_3$ is the expected change in $Y$ holding all other variables fixed and when $X_3$ (gender) is switched from the reference category (1 - male) to the other category (2 - female).</span>
<span id="cb36-87"><a href="#cb36-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-88"><a href="#cb36-88" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>$\hat \beta_4$ is the expected change in $Y$ holding all other variables fixed and when $X_4$ (routine 2 indicator) is switched from the reference category (routine 1) to the second category (routine 2).</span>
<span id="cb36-89"><a href="#cb36-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-90"><a href="#cb36-90" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>$\hat \beta_5$ is the expected change in $Y$ holding all other variables fixed and when $X_5$ (routine 3 indicator) is switched from the reference category (routine 1) to the third category (routine 3).</span>
<span id="cb36-91"><a href="#cb36-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-94"><a href="#cb36-94" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb36-95"><a href="#cb36-95" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">=</span> <span class="fu">lm</span>(weight_loss<span class="sc">~</span>hours<span class="sc">+</span>effort<span class="sc">+</span><span class="fu">factor</span>(gender)<span class="sc">+</span><span class="fu">factor</span>(routine), </span>
<span id="cb36-96"><a href="#cb36-96" aria-hidden="true" tabindex="-1"></a>         <span class="at">data=</span>df)</span>
<span id="cb36-97"><a href="#cb36-97" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span>
<span id="cb36-98"><a href="#cb36-98" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb36-99"><a href="#cb36-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-100"><a href="#cb36-100" aria-hidden="true" tabindex="-1"></a><span class="fu">## Interpret the Estimates of the Parameters </span></span>
<span id="cb36-101"><a href="#cb36-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-102"><a href="#cb36-102" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>As described above, $\hat \beta_0$ is the expected value of $Y$ when all the continuous predictors are 0 and the categorical predictor indicators $X_3$, $X_4$, $X_5$ are all 0 (i.e., all categorical predictors are in their reference categories).</span>
<span id="cb36-103"><a href="#cb36-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-104"><a href="#cb36-104" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>In other words, if we had an observation who was male, did routine 1, averaged 0 hours of exercise a day, and put in 0 (minimal) effort into exercising, their predicted weight loss would be equal to the intercept of -19.36311. (i.e., an increase in weight)</span>
<span id="cb36-105"><a href="#cb36-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-106"><a href="#cb36-106" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>As described above, $\hat \beta_1$ is the expected change in $Y$ holding all other variables fixed and when $X_1$ (average hours spent exercising in a day) increases by one unit.</span>
<span id="cb36-107"><a href="#cb36-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-108"><a href="#cb36-108" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>Hence for a unit increase in average hours spent exercising in a day, we expect a person's weight loss to increase by 3.29.</span>
<span id="cb36-109"><a href="#cb36-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-110"><a href="#cb36-110" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>As described above, $\hat \beta_2$ is the expected change in $Y$ holding all other variables fixed and when $X_2$ (amount of effort put into exercising) increases by one unit.</span>
<span id="cb36-111"><a href="#cb36-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-112"><a href="#cb36-112" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>Hence for a unit increase in the amount of physical effort put into exercising, we expect a person's weight loss to increase by 0.68967.</span>
<span id="cb36-113"><a href="#cb36-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-114"><a href="#cb36-114" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>As described above, $\hat \beta_3$ is the expected change in $Y$ holding all other variables fixed and when $X_3$ (gender) is switched from the reference category (1 - male) to the other category (2 - female).</span>
<span id="cb36-115"><a href="#cb36-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-116"><a href="#cb36-116" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>So if we had two observations with all predictors being equal, but with the only difference between them being gender - we would predict the female's weight loss to be 0.0561 greater than the male.</span>
<span id="cb36-117"><a href="#cb36-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-118"><a href="#cb36-118" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>As described above, $\hat \beta_4$ is the expected change in $Y$ holding all other variables fixed and when $X_4$ (routine 2 indicator) is switched from the reference category (routine 1) to the second category (routine 2). In this case, the value of $X_4$ would change from 0 to 1.</span>
<span id="cb36-119"><a href="#cb36-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-120"><a href="#cb36-120" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>So if we had two observations with all predictors being equal, but with the only difference between them being that one did exercise routine 2 and the other did routine 1 - we would predict the individual who did routine 2 to have an additional weight loss of 18.36.</span>
<span id="cb36-121"><a href="#cb36-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-122"><a href="#cb36-122" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>As described above, $\hat \beta_5$ is the expected change in $Y$ holding all other variables fixed and when $X_5$ (routine 3 indicator) is switched from the reference category (routine 1) to the third category (routine 3). In this case, the value of $X_5$ would change from 0 to 1.</span>
<span id="cb36-123"><a href="#cb36-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-124"><a href="#cb36-124" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>So if we had two observations with all predictors being equal, but with the only difference between them being that one did exercise routine 3 and the other did routine 1 - we would predict the individual who did routine 3 to have a reduction in weight loss of -11.42.</span>
<span id="cb36-125"><a href="#cb36-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-126"><a href="#cb36-126" aria-hidden="true" tabindex="-1"></a><span class="fu">## Which values of the categorical predictor variables will lead to the largest reduction in weight?</span></span>
<span id="cb36-127"><a href="#cb36-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-128"><a href="#cb36-128" aria-hidden="true" tabindex="-1"></a>From our summary output, we can see that:</span>
<span id="cb36-129"><a href="#cb36-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-130"><a href="#cb36-130" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>When the categorical variable *gender* is 2 (female), there is an increase in weight loss of 0.056. This is a minor difference.</span>
<span id="cb36-131"><a href="#cb36-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-132"><a href="#cb36-132" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>When the categorical variable *routine* is 2 (so exercise routine 2), there is an increase in weight loss of 18.36. This is a large difference compared to both the reference routine (routine 1) and routine 3 (which leads to a *reduction in weight loss* of -11.42).</span>
<span id="cb36-133"><a href="#cb36-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-134"><a href="#cb36-134" aria-hidden="true" tabindex="-1"></a>So the combination of gender being *female* and routine being *2* will lead to the largest reduction in weight.</span>
<span id="cb36-135"><a href="#cb36-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-136"><a href="#cb36-136" aria-hidden="true" tabindex="-1"></a><span class="fu">## The effect and significance of the categorical variable **routine** in our model.</span></span>
<span id="cb36-137"><a href="#cb36-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-138"><a href="#cb36-138" aria-hidden="true" tabindex="-1"></a>In the above, we noted that:</span>
<span id="cb36-139"><a href="#cb36-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-140"><a href="#cb36-140" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>When the categorical variable *routine* is 2 (so exercise routine 2), there is an increase in weight loss of 18.36 holding all other variables constant.</span>
<span id="cb36-141"><a href="#cb36-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-142"><a href="#cb36-142" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Routine 3 leads to a *reduction in weight loss* of 11.42, holding all other variables constant.</span>
<span id="cb36-143"><a href="#cb36-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-144"><a href="#cb36-144" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>Both routine 2 and routine 3 have high significance levels which are less that $2e-16$. These are far below the typical significance level of 0.05.</span>
<span id="cb36-145"><a href="#cb36-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-146"><a href="#cb36-146" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>This is in contrast to gender which we can see has a significance level of 0.913.</span>
<span id="cb36-147"><a href="#cb36-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-148"><a href="#cb36-148" aria-hidden="true" tabindex="-1"></a>Hence we can say that routine has a very strong effect in the model given the low p-values and high coefficient values.</span>
<span id="cb36-149"><a href="#cb36-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-150"><a href="#cb36-150" aria-hidden="true" tabindex="-1"></a><span class="fu">## Hypothesis Testing</span></span>
<span id="cb36-151"><a href="#cb36-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-152"><a href="#cb36-152" aria-hidden="true" tabindex="-1"></a><span class="fu">### Interpreting the F-statistic</span></span>
<span id="cb36-153"><a href="#cb36-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-154"><a href="#cb36-154" aria-hidden="true" tabindex="-1"></a>The F statistic output is given as 524.9 on 5 and 594 DF, p-value: <span class="sc">\&lt;</span> 2.2e-16.</span>
<span id="cb36-155"><a href="#cb36-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-156"><a href="#cb36-156" aria-hidden="true" tabindex="-1"></a>This is testing a reduced model: $$</span>
<span id="cb36-157"><a href="#cb36-157" aria-hidden="true" tabindex="-1"></a> Y =  \beta_0</span>
<span id="cb36-158"><a href="#cb36-158" aria-hidden="true" tabindex="-1"></a>$$ against the full model: $$</span>
<span id="cb36-159"><a href="#cb36-159" aria-hidden="true" tabindex="-1"></a> Y =  \beta_0 +  \beta_1X_{1} +  \beta_2X_{2} +  \beta_3X_{3} +   \beta_4X_{4} +   \beta_5X_{5}</span>
<span id="cb36-160"><a href="#cb36-160" aria-hidden="true" tabindex="-1"></a> $$</span>
<span id="cb36-161"><a href="#cb36-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-162"><a href="#cb36-162" aria-hidden="true" tabindex="-1"></a>The null hypothesis is: $$</span>
<span id="cb36-163"><a href="#cb36-163" aria-hidden="true" tabindex="-1"></a>H_0:  \beta_1 =  \beta_2 =  \beta_3 =  \beta_4 =  \beta_5 = 0</span>
<span id="cb36-164"><a href="#cb36-164" aria-hidden="true" tabindex="-1"></a>$$ And the alternative hypothesis is: $$</span>
<span id="cb36-165"><a href="#cb36-165" aria-hidden="true" tabindex="-1"></a>H_1: \text{at least one of }  \beta_1, ...,  \beta_5 \neq 0.</span>
<span id="cb36-166"><a href="#cb36-166" aria-hidden="true" tabindex="-1"></a>$$ The F-statistic for this is found to be $F = 524.9$, and the p-value on 5 and 594 degrees of freedom $P(F&gt;524.9)$ is less than $2.2e-16.$</span>
<span id="cb36-167"><a href="#cb36-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-168"><a href="#cb36-168" aria-hidden="true" tabindex="-1"></a>We can see that this rounds to 0 when we find it below:</span>
<span id="cb36-169"><a href="#cb36-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-172"><a href="#cb36-172" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb36-173"><a href="#cb36-173" aria-hidden="true" tabindex="-1"></a>F <span class="ot">=</span> <span class="fl">524.9</span></span>
<span id="cb36-174"><a href="#cb36-174" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">pf</span>(F, <span class="dv">5</span>, <span class="dv">594</span>)</span>
<span id="cb36-175"><a href="#cb36-175" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb36-176"><a href="#cb36-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-177"><a href="#cb36-177" aria-hidden="true" tabindex="-1"></a>Therefore we reject the null hypothesis and find that at least one of the predictor variables $\beta_1, ..., \beta_5$ (i.e., hours, effort, gender, routine) is non-zero.</span>
<span id="cb36-178"><a href="#cb36-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-179"><a href="#cb36-179" aria-hidden="true" tabindex="-1"></a><span class="fu">### Testing the hypothesis $H_0: \beta_1 = \beta_2 = 0$</span></span>
<span id="cb36-180"><a href="#cb36-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-181"><a href="#cb36-181" aria-hidden="true" tabindex="-1"></a>In order to test this hypothesis we will use the output of a type 2 ANOVA.</span>
<span id="cb36-182"><a href="#cb36-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-185"><a href="#cb36-185" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb36-186"><a href="#cb36-186" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(fit, <span class="at">type=</span><span class="dv">2</span>)</span>
<span id="cb36-187"><a href="#cb36-187" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb36-188"><a href="#cb36-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-189"><a href="#cb36-189" aria-hidden="true" tabindex="-1"></a>Now we will calculate the F statistic:</span>
<span id="cb36-190"><a href="#cb36-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-193"><a href="#cb36-193" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb36-194"><a href="#cb36-194" aria-hidden="true" tabindex="-1"></a>numerator <span class="ot">=</span> (<span class="dv">1510</span><span class="sc">+</span><span class="dv">7644</span>)<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb36-195"><a href="#cb36-195" aria-hidden="true" tabindex="-1"></a>denominator <span class="ot">=</span> <span class="dv">23280</span><span class="sc">/</span><span class="dv">594</span></span>
<span id="cb36-196"><a href="#cb36-196" aria-hidden="true" tabindex="-1"></a>F_test <span class="ot">=</span> numerator <span class="sc">/</span> denominator</span>
<span id="cb36-197"><a href="#cb36-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-198"><a href="#cb36-198" aria-hidden="true" tabindex="-1"></a><span class="co"># note there are 2 params - so we use 2 df</span></span>
<span id="cb36-199"><a href="#cb36-199" aria-hidden="true" tabindex="-1"></a>F_crit <span class="ot">=</span> <span class="fu">qf</span>(<span class="fl">0.05</span>, <span class="dv">2</span>, <span class="dv">594</span>,<span class="at">lower.tail =</span> <span class="dv">0</span>)</span>
<span id="cb36-200"><a href="#cb36-200" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"F test statistic:"</span>);<span class="fu">print</span>(F_test)</span>
<span id="cb36-201"><a href="#cb36-201" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"F critical:"</span>);<span class="fu">print</span>(F_crit)</span>
<span id="cb36-202"><a href="#cb36-202" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb36-203"><a href="#cb36-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-204"><a href="#cb36-204" aria-hidden="true" tabindex="-1"></a>We find that our test stat $F=116.78 &gt; F_{0.05, 2, 594} = 3.01$.</span>
<span id="cb36-205"><a href="#cb36-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-206"><a href="#cb36-206" aria-hidden="true" tabindex="-1"></a>Hence we reject the null hypothesis that the coefficients for the variables *hours* and *effort* are equal to 0 given that the categorical predictors *gender* and *routine* are in the model.</span>
<span id="cb36-207"><a href="#cb36-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-208"><a href="#cb36-208" aria-hidden="true" tabindex="-1"></a><span class="fu">## Interpreting the Adjusted R-squared Value</span></span>
<span id="cb36-209"><a href="#cb36-209" aria-hidden="true" tabindex="-1"></a>The adjusted R-squared value from the summary output is 0.8139. This adjusted R-squared value indicates that *approximately* 81.39% of the variability in the dependent variable is accounted for by the model, after adjusting for the number of predictors. This is a high value, suggesting that the model fits the data well.</span>
<span id="cb36-210"><a href="#cb36-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-211"><a href="#cb36-211" aria-hidden="true" tabindex="-1"></a>The adjusted R-squared value adjusts adjusts multiple R-squared by dividing each sum of squares by its associated degrees of freedom. Differences include:</span>
<span id="cb36-212"><a href="#cb36-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-213"><a href="#cb36-213" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>$R^2_a$ can be negative and only increases if the variation in Y accounted for by the added predictor is greater than the penalty.</span>
<span id="cb36-214"><a href="#cb36-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-215"><a href="#cb36-215" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>In contrast, $R^2$ is always between 0 and 1 and can only become larger as more explanatory variables are added to the model.</span>
<span id="cb36-216"><a href="#cb36-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-217"><a href="#cb36-217" aria-hidden="true" tabindex="-1"></a>These differences are more clear when we look at the equations: $$</span>
<span id="cb36-218"><a href="#cb36-218" aria-hidden="true" tabindex="-1"></a>R^2 = 1 - \frac{SSE}{SST}</span>
<span id="cb36-219"><a href="#cb36-219" aria-hidden="true" tabindex="-1"></a>$$ $$</span>
<span id="cb36-220"><a href="#cb36-220" aria-hidden="true" tabindex="-1"></a>R^2_a = 1 - \frac{\frac{SSE}{n-p}}{\frac{SST}{n-1}}</span>
<span id="cb36-221"><a href="#cb36-221" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb36-222"><a href="#cb36-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-223"><a href="#cb36-223" aria-hidden="true" tabindex="-1"></a><span class="fu">## Predicting Weight Loss </span></span>
<span id="cb36-224"><a href="#cb36-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-225"><a href="#cb36-225" aria-hidden="true" tabindex="-1"></a>How much loss would we predict for a male person, exercising 3 hours a day under routine number 2 with an effort of 25? </span>
<span id="cb36-226"><a href="#cb36-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-227"><a href="#cb36-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-228"><a href="#cb36-228" aria-hidden="true" tabindex="-1"></a>The predicted weight loss would be given by: </span>
<span id="cb36-229"><a href="#cb36-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-230"><a href="#cb36-230" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb36-231"><a href="#cb36-231" aria-hidden="true" tabindex="-1"></a>\begin{align*}</span>
<span id="cb36-232"><a href="#cb36-232" aria-hidden="true" tabindex="-1"></a>\text{Predicted Weight Loss} &amp;= -19.36 <span class="sc">\\</span></span>
<span id="cb36-233"><a href="#cb36-233" aria-hidden="true" tabindex="-1"></a>                             &amp;\quad + 3.29(\text{hours}) <span class="sc">\\</span></span>
<span id="cb36-234"><a href="#cb36-234" aria-hidden="true" tabindex="-1"></a>                             &amp;\quad + 0.69(\text{effort}) <span class="sc">\\</span></span>
<span id="cb36-235"><a href="#cb36-235" aria-hidden="true" tabindex="-1"></a>                             &amp;\quad + 0.06(\text{gender2}) <span class="sc">\\</span></span>
<span id="cb36-236"><a href="#cb36-236" aria-hidden="true" tabindex="-1"></a>                             &amp;\quad + 18.36(\text{routine2}) <span class="sc">\\</span></span>
<span id="cb36-237"><a href="#cb36-237" aria-hidden="true" tabindex="-1"></a>                             &amp;\quad - 11.42(\text{routine3})</span>
<span id="cb36-238"><a href="#cb36-238" aria-hidden="true" tabindex="-1"></a>\end{align*}</span>
<span id="cb36-239"><a href="#cb36-239" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb36-240"><a href="#cb36-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-241"><a href="#cb36-241" aria-hidden="true" tabindex="-1"></a>Substituting in the values: </span>
<span id="cb36-242"><a href="#cb36-242" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb36-243"><a href="#cb36-243" aria-hidden="true" tabindex="-1"></a>\begin{align*}</span>
<span id="cb36-244"><a href="#cb36-244" aria-hidden="true" tabindex="-1"></a>\text{Predicted Weight Loss} &amp;= -19.36 <span class="sc">\\</span></span>
<span id="cb36-245"><a href="#cb36-245" aria-hidden="true" tabindex="-1"></a>                             &amp;\quad + 3.29 \times 3 <span class="sc">\\</span></span>
<span id="cb36-246"><a href="#cb36-246" aria-hidden="true" tabindex="-1"></a>                             &amp;\quad + 0.69 \times 25 <span class="sc">\\</span></span>
<span id="cb36-247"><a href="#cb36-247" aria-hidden="true" tabindex="-1"></a>                             &amp;\quad + 0.06 \times 0 <span class="sc">\\</span></span>
<span id="cb36-248"><a href="#cb36-248" aria-hidden="true" tabindex="-1"></a>                             &amp;\quad + 18.36 \times 1 <span class="sc">\\</span></span>
<span id="cb36-249"><a href="#cb36-249" aria-hidden="true" tabindex="-1"></a>                             &amp;\quad - 11.42 \times 0 <span class="sc">\\</span></span>
<span id="cb36-250"><a href="#cb36-250" aria-hidden="true" tabindex="-1"></a>                             &amp;= 26.12</span>
<span id="cb36-251"><a href="#cb36-251" aria-hidden="true" tabindex="-1"></a>\end{align*}</span>
<span id="cb36-252"><a href="#cb36-252" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb36-253"><a href="#cb36-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-254"><a href="#cb36-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-255"><a href="#cb36-255" aria-hidden="true" tabindex="-1"></a>Which we can also find through R:</span>
<span id="cb36-256"><a href="#cb36-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-259"><a href="#cb36-259" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb36-260"><a href="#cb36-260" aria-hidden="true" tabindex="-1"></a>predicted_loss <span class="ot">=</span> fit<span class="sc">$</span>coefficients[<span class="dv">1</span>] <span class="sc">+</span> <span class="dv">3</span><span class="sc">*</span>fit<span class="sc">$</span>coefficients[<span class="dv">2</span>] <span class="sc">+</span> <span class="dv">25</span><span class="sc">*</span>fit<span class="sc">$</span>coefficients[<span class="dv">3</span>] <span class="sc">+</span> <span class="dv">0</span><span class="sc">*</span>fit<span class="sc">$</span>coefficients[<span class="dv">4</span>] <span class="sc">+</span> <span class="dv">1</span><span class="sc">*</span>fit<span class="sc">$</span>coefficients[<span class="dv">5</span>] <span class="sc">+</span> <span class="dv">0</span><span class="sc">*</span>fit<span class="sc">$</span>coefficients[<span class="dv">6</span>]</span>
<span id="cb36-261"><a href="#cb36-261" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(predicted_loss)</span>
<span id="cb36-262"><a href="#cb36-262" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb36-263"><a href="#cb36-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-264"><a href="#cb36-264" aria-hidden="true" tabindex="-1"></a>Therefore we would predict a weight loss of 26.12.</span>
<span id="cb36-265"><a href="#cb36-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-266"><a href="#cb36-266" aria-hidden="true" tabindex="-1"></a><span class="fu">### 95% Prediction Interval for Predicted Weight Loss</span></span>
<span id="cb36-267"><a href="#cb36-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-268"><a href="#cb36-268" aria-hidden="true" tabindex="-1"></a>We find the values of the 95% prediction interval for this individual using the R code below:</span>
<span id="cb36-269"><a href="#cb36-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-272"><a href="#cb36-272" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb36-273"><a href="#cb36-273" aria-hidden="true" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">hours=</span><span class="dv">3</span>, <span class="at">effort=</span><span class="dv">25</span>, </span>
<span id="cb36-274"><a href="#cb36-274" aria-hidden="true" tabindex="-1"></a>                      <span class="at">gender=</span><span class="fu">factor</span>(<span class="st">"1"</span>, <span class="at">levels=</span><span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"2"</span>)), </span>
<span id="cb36-275"><a href="#cb36-275" aria-hidden="true" tabindex="-1"></a>                      <span class="at">routine=</span><span class="fu">factor</span>(<span class="st">"2"</span>, <span class="at">levels=</span><span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"2"</span>, <span class="st">"3"</span>)))</span>
<span id="cb36-276"><a href="#cb36-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-277"><a href="#cb36-277" aria-hidden="true" tabindex="-1"></a>prediction <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit, <span class="at">newdata=</span>newdata, <span class="at">interval=</span><span class="st">"prediction"</span>, <span class="at">level=</span><span class="fl">0.95</span>)</span>
<span id="cb36-278"><a href="#cb36-278" aria-hidden="true" tabindex="-1"></a>prediction</span>
<span id="cb36-279"><a href="#cb36-279" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb36-280"><a href="#cb36-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-281"><a href="#cb36-281" aria-hidden="true" tabindex="-1"></a>The prediction interval gives the range of values within which we expect the actual observed value to lie with 95% confidence, taking into account the error in the prediction. This interval is between 13.73 and 38.52.</span>
<span id="cb36-282"><a href="#cb36-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-283"><a href="#cb36-283" aria-hidden="true" tabindex="-1"></a><span class="fu">## Interaction Effects </span></span>
<span id="cb36-284"><a href="#cb36-284" aria-hidden="true" tabindex="-1"></a>Is there an interaction between the predictor variables effort and routine a person is enrolled in?</span>
<span id="cb36-285"><a href="#cb36-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-286"><a href="#cb36-286" aria-hidden="true" tabindex="-1"></a>The below scatter plot matrix demonstrates that there are diverging lines (different slopes) - this indicates there is an interaction between these predictor variables.</span>
<span id="cb36-287"><a href="#cb36-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-288"><a href="#cb36-288" aria-hidden="true" tabindex="-1"></a>We can fit a model to more rigorously test this hypothesis. Our proposed equation is:</span>
<span id="cb36-289"><a href="#cb36-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-290"><a href="#cb36-290" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb36-291"><a href="#cb36-291" aria-hidden="true" tabindex="-1"></a>\begin{align*}</span>
<span id="cb36-292"><a href="#cb36-292" aria-hidden="true" tabindex="-1"></a>Y_i &amp;= \beta_0 + \beta_1X_{i, 1} + \beta_2X_{i,2} + \beta_3X_{i,3} + \beta_4X_{i,4} + \beta_5X_{i,5} <span class="sc">\\</span></span>
<span id="cb36-293"><a href="#cb36-293" aria-hidden="true" tabindex="-1"></a>    &amp;\quad + \beta_6(X_{i,2} \times X_{i, 4}) + \beta_7(X_{i,2} \times X_{i, 5}) + \epsilon_i, \quad i = 1, ..., n</span>
<span id="cb36-294"><a href="#cb36-294" aria-hidden="true" tabindex="-1"></a>\end{align*}</span>
<span id="cb36-295"><a href="#cb36-295" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb36-296"><a href="#cb36-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-297"><a href="#cb36-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-298"><a href="#cb36-298" aria-hidden="true" tabindex="-1"></a>To make this more clear in terms of the predictors, we can also express it as:</span>
<span id="cb36-299"><a href="#cb36-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-300"><a href="#cb36-300" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb36-301"><a href="#cb36-301" aria-hidden="true" tabindex="-1"></a>\begin{align*}</span>
<span id="cb36-302"><a href="#cb36-302" aria-hidden="true" tabindex="-1"></a>\text{Predicted Weight Loss} &amp;= \beta_0 + \beta_1(\text{hours}) + \beta_2(\text{effort}) + \beta_3(\text{gender2}) <span class="sc">\\</span></span>
<span id="cb36-303"><a href="#cb36-303" aria-hidden="true" tabindex="-1"></a>                             &amp;\quad + \beta_4(\text{routine2}) + \beta_5(\text{routine3}) <span class="sc">\\</span></span>
<span id="cb36-304"><a href="#cb36-304" aria-hidden="true" tabindex="-1"></a>                             &amp;\quad + \beta_6(\text{effort} \times \text{routine2}) + \beta_7(\text{effort} \times \text{routine3}),</span>
<span id="cb36-305"><a href="#cb36-305" aria-hidden="true" tabindex="-1"></a>\end{align*}</span>
<span id="cb36-306"><a href="#cb36-306" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb36-307"><a href="#cb36-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-308"><a href="#cb36-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-309"><a href="#cb36-309" aria-hidden="true" tabindex="-1"></a>where the interaction terms, $\beta_6(\text{effort} \times \text{routine2})$ and $\beta_7(\text{effort} \times \text{routine3})$,  capture the additional effect on the predicted weight loss that is due to the combination of effort with each level of routine beyond the *main effects* of routine and effort by themselves.</span>
<span id="cb36-310"><a href="#cb36-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-313"><a href="#cb36-313" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb36-314"><a href="#cb36-314" aria-hidden="true" tabindex="-1"></a><span class="fu">scatterplotMatrix</span>(<span class="sc">~</span>effort <span class="sc">+</span> weight_loss <span class="sc">|</span><span class="fu">factor</span>(routine),<span class="at">data=</span>df)</span>
<span id="cb36-315"><a href="#cb36-315" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb36-316"><a href="#cb36-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-317"><a href="#cb36-317" aria-hidden="true" tabindex="-1"></a><span class="fu">### Modelling the Interaction</span></span>
<span id="cb36-318"><a href="#cb36-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-319"><a href="#cb36-319" aria-hidden="true" tabindex="-1"></a>In our new model with interaction added, we observe that the fit has improved as the *adjusted* R-squared value has increased from 0.8139 to 0.845.</span>
<span id="cb36-320"><a href="#cb36-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-321"><a href="#cb36-321" aria-hidden="true" tabindex="-1"></a>We can also observe that the interactions between effort and routines 2 and 3 have extremely low p-values, indicating their importance to the model.</span>
<span id="cb36-322"><a href="#cb36-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-325"><a href="#cb36-325" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb36-326"><a href="#cb36-326" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">=</span> <span class="fu">lm</span>(weight_loss<span class="sc">~</span>hours<span class="sc">+</span>effort<span class="sc">+</span><span class="fu">factor</span>(gender)<span class="sc">+</span><span class="fu">factor</span>(routine) <span class="sc">+</span> effort<span class="sc">*</span><span class="fu">factor</span>(routine), </span>
<span id="cb36-327"><a href="#cb36-327" aria-hidden="true" tabindex="-1"></a>         <span class="at">data=</span>df)</span>
<span id="cb36-328"><a href="#cb36-328" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span>
<span id="cb36-329"><a href="#cb36-329" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb36-330"><a href="#cb36-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-331"><a href="#cb36-331" aria-hidden="true" tabindex="-1"></a><span class="fu"># Diagnostic tests on the regression model</span></span>
<span id="cb36-332"><a href="#cb36-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-333"><a href="#cb36-333" aria-hidden="true" tabindex="-1"></a><span class="fu">## Linearity Assumption</span></span>
<span id="cb36-334"><a href="#cb36-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-335"><a href="#cb36-335" aria-hidden="true" tabindex="-1"></a>The consequences of the model not satisfying the linearity assumption are that it will lead to biased and inconsistent estimates.</span>
<span id="cb36-336"><a href="#cb36-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-337"><a href="#cb36-337" aria-hidden="true" tabindex="-1"></a>We can check the linearity assumption of our model by using scatterplots, added variable plots, and component-plus-residual plots.</span>
<span id="cb36-338"><a href="#cb36-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-339"><a href="#cb36-339" aria-hidden="true" tabindex="-1"></a><span class="fu">### Scatterplots</span></span>
<span id="cb36-340"><a href="#cb36-340" aria-hidden="true" tabindex="-1"></a>Examining the scatterplots first we see that we could fit a line through the scatterplots for our continuous predictors against weight_loss. However, we can see that there would be a lot of points far away from this line and hence we will investigate this further. In addition, we note that the weight_loss distribution is right-skewed.</span>
<span id="cb36-341"><a href="#cb36-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-344"><a href="#cb36-344" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb36-345"><a href="#cb36-345" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(df)</span>
<span id="cb36-346"><a href="#cb36-346" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb36-347"><a href="#cb36-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-348"><a href="#cb36-348" aria-hidden="true" tabindex="-1"></a><span class="fu">### Added Variable Plots</span></span>
<span id="cb36-349"><a href="#cb36-349" aria-hidden="true" tabindex="-1"></a>Now examining added-variable plots, we see that the lines generally fit the scatterplot well despite some outliers for our continuous predictors 'hours' and 'effort'. The straight lines and the lack of a pattern we observe in the scattering of the points around the line are a good sign that the model satisfies the linearity assumption.</span>
<span id="cb36-350"><a href="#cb36-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-353"><a href="#cb36-353" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb36-354"><a href="#cb36-354" aria-hidden="true" tabindex="-1"></a><span class="fu">avPlots</span>(fit)</span>
<span id="cb36-355"><a href="#cb36-355" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb36-356"><a href="#cb36-356" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-357"><a href="#cb36-357" aria-hidden="true" tabindex="-1"></a>We do not check the component-plus-residual plots as they are not available for models with interactions.</span>
<span id="cb36-358"><a href="#cb36-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-359"><a href="#cb36-359" aria-hidden="true" tabindex="-1"></a>In conclusion, we can say that the model seems to satisfy the linearity assumption based on our observation of the scatterplot matrix and added-variable plots.</span>
<span id="cb36-360"><a href="#cb36-360" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-361"><a href="#cb36-361" aria-hidden="true" tabindex="-1"></a><span class="fu">## Added Variable Plots in Detail</span></span>
<span id="cb36-362"><a href="#cb36-362" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-363"><a href="#cb36-363" aria-hidden="true" tabindex="-1"></a>We used an added variable plot in the previous question to test the linearity assumption.</span>
<span id="cb36-364"><a href="#cb36-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-365"><a href="#cb36-365" aria-hidden="true" tabindex="-1"></a>To elaborate further, it provides a way to visualise the relationship between the dependent variable (weight_loss) and one of the independent variables (hours, say) while controlling for the presence of the other independent variables in the model.</span>
<span id="cb36-366"><a href="#cb36-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-367"><a href="#cb36-367" aria-hidden="true" tabindex="-1"></a>Through this it can show us whether the relationship between the independent variable and dependent variable is linear when the effects of the other variables are removed. In addition, it helps us identify outliers and influential observations.</span>
<span id="cb36-368"><a href="#cb36-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-369"><a href="#cb36-369" aria-hidden="true" tabindex="-1"></a><span class="fu">### Interpretations for all predictor variables in the model</span></span>
<span id="cb36-370"><a href="#cb36-370" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-371"><a href="#cb36-371" aria-hidden="true" tabindex="-1"></a>Hours</span>
<span id="cb36-372"><a href="#cb36-372" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-373"><a href="#cb36-373" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The added variable plot for hours shows a linear relationship with the dependent variable weight_loss. The slope is positive, suggesting that once the other variables are accounted for, hours is a strong predictor. The points are scattered roughly evenly about the line despite some outliers.</span>
<span id="cb36-374"><a href="#cb36-374" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-375"><a href="#cb36-375" aria-hidden="true" tabindex="-1"></a>Effort</span>
<span id="cb36-376"><a href="#cb36-376" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-377"><a href="#cb36-377" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The added variable plot for effort shows a linear relationship with the dependent variable weight_loss. The slope is greater than the slope for hours, suggesting that once the other variables are accounted for, effort is a very strong predictor. There is a notable concentration of the points around 0.</span>
<span id="cb36-378"><a href="#cb36-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-379"><a href="#cb36-379" aria-hidden="true" tabindex="-1"></a>Gender</span>
<span id="cb36-380"><a href="#cb36-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-381"><a href="#cb36-381" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The plot for the categorical variable gender shows a flat regression line, which implies that there is no significant linear relationship between gender and weight_loss once the other variables are accounted for. This agrees with high p-value in the summary output of our model.</span>
<span id="cb36-382"><a href="#cb36-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-383"><a href="#cb36-383" aria-hidden="true" tabindex="-1"></a>Routine</span>
<span id="cb36-384"><a href="#cb36-384" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-385"><a href="#cb36-385" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The plots for the categorical variable routine differ between routine2 and routine3. Routine2 has an almost flat line indicating that there is no significant linear relationship between this routine and weight_loss - this also agrees with the high p-value for this predictor in the summary output. In contrast, routine3 has a more positive slope which indicates a stronger linear relationship with weight_loss. Again, this agrees with the low p-value in the summary output.</span>
<span id="cb36-386"><a href="#cb36-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-387"><a href="#cb36-387" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>In both of these plots there is a concentration of points around 0.</span>
<span id="cb36-388"><a href="#cb36-388" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-389"><a href="#cb36-389" aria-hidden="true" tabindex="-1"></a>Interaction between effort and routine</span>
<span id="cb36-390"><a href="#cb36-390" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-391"><a href="#cb36-391" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The interaction plots show that the linear relationship between effort and weight_loss changes with the different levels of the categorical variable routine.</span>
<span id="cb36-392"><a href="#cb36-392" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-393"><a href="#cb36-393" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>Effort<span class="sc">\*</span>routine2 shows a slight positive linear relationship with weight loss once the other variables are accounted for. The points are mostly scattered evenly around the line with a concentration around 0.</span>
<span id="cb36-394"><a href="#cb36-394" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-395"><a href="#cb36-395" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>Effort<span class="sc">\*</span>routine3 shows a stronger negative linear relationship with weight loss once the other variables are accounted for. The points are mostly scattered evenly around the line with a concentration around 0.</span>
<span id="cb36-396"><a href="#cb36-396" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-399"><a href="#cb36-399" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb36-400"><a href="#cb36-400" aria-hidden="true" tabindex="-1"></a><span class="fu">avPlots</span>(fit)</span>
<span id="cb36-401"><a href="#cb36-401" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb36-402"><a href="#cb36-402" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-403"><a href="#cb36-403" aria-hidden="true" tabindex="-1"></a><span class="fu"># ANOVA</span></span>
<span id="cb36-404"><a href="#cb36-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-405"><a href="#cb36-405" aria-hidden="true" tabindex="-1"></a><span class="fu">## ANOVA Type I </span></span>
<span id="cb36-406"><a href="#cb36-406" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-407"><a href="#cb36-407" aria-hidden="true" tabindex="-1"></a>R's default ANOVA function is a Type 1 ANOVA. This anova function behaves in a cumulative way - sequentially adding each predictor.</span>
<span id="cb36-408"><a href="#cb36-408" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-409"><a href="#cb36-409" aria-hidden="true" tabindex="-1"></a>For each predictor, the null hypothesis $H_0$ is that the predictor does not explain a significant amount of variance in the response variable weight_loss. The alternative hypothesis $H_1$ is that the predictor does not explain a significant amount of variance.</span>
<span id="cb36-410"><a href="#cb36-410" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-411"><a href="#cb36-411" aria-hidden="true" tabindex="-1"></a>To illustrate this consider the following:</span>
<span id="cb36-412"><a href="#cb36-412" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-413"><a href="#cb36-413" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The hours line:</span>
<span id="cb36-414"><a href="#cb36-414" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-415"><a href="#cb36-415" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>Compares $\hat{Y} = \hat{\beta_0}$ to $\hat{Y} = \hat{\beta_0} + \hat{\beta_1}hours$. The variation (sum of squares) in Y that is explained by including hours given that no other variables are in the model is 892. The **test statistic** F is 27.33 and the **p-value** is 2.383e-07. Based on this low p-value we reject the null hypothesis and **conclude** that 'hours' significantly explains variance in 'weight_loss.'</span>
<span id="cb36-416"><a href="#cb36-416" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-417"><a href="#cb36-417" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The effort line:</span>
<span id="cb36-418"><a href="#cb36-418" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-419"><a href="#cb36-419" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>Compares $\hat{Y} = \hat{\beta_0} + \hat{\beta_1}hours$ to $\hat{Y} = \hat{\beta_0} + \hat{\beta_1}hours + \hat{\beta_2} effort$. The variation (sum of squares) in Y that is explained by including effort given that hours is already in the model is 13922 The **test statistic** F is 426.53 and the **p-value** is less than 2.2e-16. Based on this low p-value we reject the null hypothesis and conclude that 'effort' significantly explains variance in 'weight_loss,' given than hours is already in the model.</span>
<span id="cb36-420"><a href="#cb36-420" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-421"><a href="#cb36-421" aria-hidden="true" tabindex="-1"></a>We can extend this explanation trivially to the remaining predictors, but I will not include this for the sake of brevity.</span>
<span id="cb36-422"><a href="#cb36-422" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-423"><a href="#cb36-423" aria-hidden="true" tabindex="-1"></a>Finally, we note that the residuals represent the variation in weight_loss that is not explained by the model. The lower the residual mean square (33), the better the model explains the data.</span>
<span id="cb36-424"><a href="#cb36-424" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-427"><a href="#cb36-427" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb36-428"><a href="#cb36-428" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit)</span>
<span id="cb36-429"><a href="#cb36-429" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb36-430"><a href="#cb36-430" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-431"><a href="#cb36-431" aria-hidden="true" tabindex="-1"></a><span class="fu">## ANOVA Type II </span></span>
<span id="cb36-434"><a href="#cb36-434" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb36-435"><a href="#cb36-435" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(fit, <span class="at">type=</span><span class="dv">2</span>)</span>
<span id="cb36-436"><a href="#cb36-436" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb36-437"><a href="#cb36-437" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-438"><a href="#cb36-438" aria-hidden="true" tabindex="-1"></a>In comparison, Type 2 ANOVA does not work in a cumulative and additive way as with the Type 1 Anova table. Instead, each row begins with the full fitted model and then compares it with a model without one of the predictor variables.</span>
<span id="cb36-439"><a href="#cb36-439" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-440"><a href="#cb36-440" aria-hidden="true" tabindex="-1"></a>Therefore, the hours line compares the residuals of: </span>
<span id="cb36-441"><a href="#cb36-441" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb36-442"><a href="#cb36-442" aria-hidden="true" tabindex="-1"></a>\begin{align*}</span>
<span id="cb36-443"><a href="#cb36-443" aria-hidden="true" tabindex="-1"></a>\text{Predicted Weight Loss} &amp;= \beta_0 + \beta_1(\text{hours}) + \beta_2(\text{effort}) + \beta_3(\text{gender2}) <span class="sc">\\</span></span>
<span id="cb36-444"><a href="#cb36-444" aria-hidden="true" tabindex="-1"></a>  &amp;\quad + \beta_4(\text{routine2}) + \beta_5(\text{routine3}) <span class="sc">\\</span></span>
<span id="cb36-445"><a href="#cb36-445" aria-hidden="true" tabindex="-1"></a>  &amp;\quad + \beta_6(\text{effort} \times \text{routine2}) + \beta_7(\text{effort} \times \text{routine3})</span>
<span id="cb36-446"><a href="#cb36-446" aria-hidden="true" tabindex="-1"></a>\end{align*}</span>
<span id="cb36-447"><a href="#cb36-447" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb36-448"><a href="#cb36-448" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-449"><a href="#cb36-449" aria-hidden="true" tabindex="-1"></a>to the residuals of:</span>
<span id="cb36-450"><a href="#cb36-450" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb36-451"><a href="#cb36-451" aria-hidden="true" tabindex="-1"></a>\begin{align*}</span>
<span id="cb36-452"><a href="#cb36-452" aria-hidden="true" tabindex="-1"></a>\text{Predicted Weight Loss} &amp;= \beta_0 + \beta_2(\text{effort}) + \beta_3(\text{gender2}) <span class="sc">\\</span></span>
<span id="cb36-453"><a href="#cb36-453" aria-hidden="true" tabindex="-1"></a>  &amp;\quad + \beta_4(\text{routine2}) + \beta_5(\text{routine3}) <span class="sc">\\</span></span>
<span id="cb36-454"><a href="#cb36-454" aria-hidden="true" tabindex="-1"></a>  &amp;\quad + \beta_6(\text{effort} \times \text{routine2}) + \beta_7(\text{effort} \times \text{routine3})</span>
<span id="cb36-455"><a href="#cb36-455" aria-hidden="true" tabindex="-1"></a>\end{align*}</span>
<span id="cb36-456"><a href="#cb36-456" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb36-457"><a href="#cb36-457" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-458"><a href="#cb36-458" aria-hidden="true" tabindex="-1"></a>(note these should be $\hat\beta$s). If there is a significant reduction in residuals when hours is included, then that term should remain in the model.</span>
<span id="cb36-459"><a href="#cb36-459" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-460"><a href="#cb36-460" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>In the case of hours then, the variation in weight_loss explained when this predictor is added into the full model is 1595 (note this is higher than in the case of the Type 1 ANOVA). The F statistic is 48.85 and the p-value is 7.463e-12. Therefore we reject the null hypothesis and conclude that this term should remain in the model.</span>
<span id="cb36-461"><a href="#cb36-461" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-462"><a href="#cb36-462" aria-hidden="true" tabindex="-1"></a>Again, we can extend this explanation trivially to the remaining predictors, but I will not include this for the sake of brevity.</span>
<span id="cb36-463"><a href="#cb36-463" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-464"><a href="#cb36-464" aria-hidden="true" tabindex="-1"></a>We can calculate the test statistic for hours manually from the output below (note there is some minor rounding error):</span>
<span id="cb36-465"><a href="#cb36-465" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-468"><a href="#cb36-468" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb36-469"><a href="#cb36-469" aria-hidden="true" tabindex="-1"></a>numerator <span class="ot">=</span> <span class="dv">1595</span> <span class="sc">/</span> <span class="dv">1</span></span>
<span id="cb36-470"><a href="#cb36-470" aria-hidden="true" tabindex="-1"></a>denominator <span class="ot">=</span> <span class="dv">19322</span> <span class="sc">/</span> <span class="dv">592</span></span>
<span id="cb36-471"><a href="#cb36-471" aria-hidden="true" tabindex="-1"></a>F_test <span class="ot">=</span> numerator <span class="sc">/</span> denominator</span>
<span id="cb36-472"><a href="#cb36-472" aria-hidden="true" tabindex="-1"></a>F_crit <span class="ot">=</span> <span class="fu">qf</span>(<span class="fl">0.05</span>, <span class="dv">1</span>, <span class="dv">592</span>,<span class="at">lower.tail =</span> <span class="dv">0</span>)</span>
<span id="cb36-473"><a href="#cb36-473" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"F test statistic:"</span>);<span class="fu">print</span>(F_test)</span>
<span id="cb36-474"><a href="#cb36-474" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"F critical:"</span>);<span class="fu">print</span>(F_crit)</span>
<span id="cb36-475"><a href="#cb36-475" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb36-476"><a href="#cb36-476" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-477"><a href="#cb36-477" aria-hidden="true" tabindex="-1"></a>And we can also calculate the adjust R-squared value using:</span>
<span id="cb36-478"><a href="#cb36-478" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-481"><a href="#cb36-481" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb36-482"><a href="#cb36-482" aria-hidden="true" tabindex="-1"></a>SSR <span class="ot">=</span> <span class="dv">1595</span> <span class="sc">+</span> <span class="dv">7644</span> <span class="sc">+</span> <span class="dv">88038</span> <span class="sc">+</span> <span class="dv">3957</span> </span>
<span id="cb36-483"><a href="#cb36-483" aria-hidden="true" tabindex="-1"></a>SST <span class="ot">=</span> SSR <span class="sc">+</span> <span class="dv">19322</span></span>
<span id="cb36-484"><a href="#cb36-484" aria-hidden="true" tabindex="-1"></a>SSE <span class="ot">=</span> <span class="dv">19322</span></span>
<span id="cb36-485"><a href="#cb36-485" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-486"><a href="#cb36-486" aria-hidden="true" tabindex="-1"></a><span class="co"># equivalent</span></span>
<span id="cb36-487"><a href="#cb36-487" aria-hidden="true" tabindex="-1"></a>R2 <span class="ot">=</span> SSR<span class="sc">/</span>SST</span>
<span id="cb36-488"><a href="#cb36-488" aria-hidden="true" tabindex="-1"></a>R2 <span class="ot">=</span> <span class="dv">1</span> <span class="sc">-</span> SSE<span class="sc">/</span>SST</span>
<span id="cb36-489"><a href="#cb36-489" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-490"><a href="#cb36-490" aria-hidden="true" tabindex="-1"></a><span class="co"># adjusted R squared - note the dfs for SSE (n-p) and SST (n-1)</span></span>
<span id="cb36-491"><a href="#cb36-491" aria-hidden="true" tabindex="-1"></a>R2a <span class="ot">=</span> <span class="dv">1</span> <span class="sc">-</span> (SSE<span class="sc">/</span>(<span class="dv">592</span>)) <span class="sc">/</span> (SST<span class="sc">/</span><span class="dv">599</span>)</span>
<span id="cb36-492"><a href="#cb36-492" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(R2a)</span>
<span id="cb36-493"><a href="#cb36-493" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>